from typing import Optional, NamedTuple, Dict, TYPE_CHECKING

from BaseClasses import ItemClassification, Item

if TYPE_CHECKING:
    from . import TBOIWorld

class ItemData(NamedTuple):
    code: Optional[int]
    classification: ItemClassification
    category: Optional[str] = None
    amount: Optional[int] = 1

class TBOIItem(Item):
    game = "The Binding of Isaac: Repentance+"

    def __init__(self, player: int, name: str, data: ItemData):
        super().__init__(name, data.classification, data.code, player)
        self.name = name
        self.classification = data.classification

# For the option "starting character", the number corresponds to the entry in this table.
character_items = [
    "Isaac", "Magdalene", "Cain", "Judas", "???",
    "Eve", "Samson",
    "Azazel", "Lazarus", "Eden", "Lost",
    "Lilith", "Keeper",
    "Apollyon", "Forgotten",
    "Bethany", "Jacob and Esau",
    "The Broken", "The Dauntless", "The Hoarder", "The Deceiver", "The Soiled",
    "The Curdled", "The Savage",
    "The Benighted", "The Enigma", "The Capricious", "The Baleful",
    "The Harlot", "The Miser",
    "The Empty", "The Fettered",
    "The Zealot", "The Deserter"
]

def get_items_table(world: Optional["TBOIWorld"]) -> Dict[str, ItemData]:
    if world is None:
        return _items_table

    for name, data in _items_table.items():
        if data.category == "Co-Op Baby":
            _items_table[name] = ItemData(data.code, ItemClassification.progression, category=data.category)

    return _items_table

_items_table: Dict[str, ItemData] = {
        "Isaac"                              : ItemData(0x27BC86A9, ItemClassification.progression, category="Character"),
        "Magdalene"                          : ItemData(0x27BC86AA, ItemClassification.progression, category="Character"),
        "Cain"                               : ItemData(0x27BC86AB, ItemClassification.progression, category="Character"),
        "Judas"                              : ItemData(0x27BC86AC, ItemClassification.progression, category="Character"),
        "The Womb"                           : ItemData(0x27BC86AD, ItemClassification.progression, category="Stage"),
        "The Harbingers"                     : ItemData(0x27BC86AE, ItemClassification.progression),
        "A Cube of Meat"                     : ItemData(0x27BC86AF, ItemClassification.progression, category="Item"),
        "The Book of Revelations"            : ItemData(0x27BC86B0, ItemClassification.progression, category="Item"),
        "A Noose"                            : ItemData(0x27BC86B1, ItemClassification.filler, category="Item"),
        "The Nail"                           : ItemData(0x27BC86B2, ItemClassification.filler, category="Item"),
        "A Quarter"                          : ItemData(0x27BC86B3, ItemClassification.filler, category="Item"),
        "A Fetus in a Jar"                   : ItemData(0x27BC86B4, ItemClassification.filler, category="Item"),
        "A Small Rock"                       : ItemData(0x27BC86B5, ItemClassification.filler, category="Item"),
        "Monstro's Tooth"                    : ItemData(0x27BC86B6, ItemClassification.filler, category="Item"),
        "Lil' Chubby"                        : ItemData(0x27BC86B7, ItemClassification.filler, category="Item"),
        "Loki's Horns"                       : ItemData(0x27BC86B8, ItemClassification.filler, category="Item"),
        "Something From The Future"          : ItemData(0x27BC86B9, ItemClassification.useful),
        "Something Cute"                     : ItemData(0x27BC86BA, ItemClassification.useful),
        "Something Sticky"                   : ItemData(0x27BC86BB, ItemClassification.useful),
        "A Cross"                            : ItemData(0x27BC86BC, ItemClassification.filler, category="Item"),
        "The Book of Sin"                    : ItemData(0x27BC86BD, ItemClassification.filler, category="Item"),
        "Little Steven"                      : ItemData(0x27BC86BE, ItemClassification.filler, category="Item"),
        "A Gamekid"                          : ItemData(0x27BC86BF, ItemClassification.filler, category="Item"),
        "Mr. Mega"                           : ItemData(0x27BC86C0, ItemClassification.filler, category="Item"),
        "The Scissors"                       : ItemData(0x27BC86C1, ItemClassification.filler, category="Item"),
        "The Parasite"                       : ItemData(0x27BC86C2, ItemClassification.filler, category="Item"),
        "???"                                : ItemData(0x27BC86C3, ItemClassification.progression, category="Character"),
        "Everything is Terrible!!!"          : ItemData(0x27BC86C4, ItemClassification.trap),
        "It Lives!"                          : ItemData(0x27BC86C5, ItemClassification.progression, category="Stage"),
        "Mom's Contact"                      : ItemData(0x27BC86C6, ItemClassification.filler, category="Item"),
        "Necronomicon"                       : ItemData(0x27BC86C7, ItemClassification.filler, category="Item"),
    #    "Basement Boy"                      : ItemData(0x27BC86C8, ItemClassification.useful),
    #    "Spelunker Boy"                     : ItemData(0x27BC86C9, ItemClassification.useful),
    #    "Dark Boy"                          : ItemData(0x27BC86CA, ItemClassification.useful),
    #    "Mama's Boy"                        : ItemData(0x27BC86CB, ItemClassification.useful),
    #    "Golden God"                        : ItemData(0x27BC86CC, ItemClassification.useful),
        "Eve"                                : ItemData(0x27BC86CD, ItemClassification.progression, category="Character"),
        "Mom's Knife"                        : ItemData(0x27BC86CE, ItemClassification.filler, category="Item"),
        "The Razor"                          : ItemData(0x27BC86CF, ItemClassification.filler, category="Item"),
        "Guardian Angel"                     : ItemData(0x27BC86D0, ItemClassification.filler, category="Item"),
        "Bomb Bag"                           : ItemData(0x27BC86D1, ItemClassification.filler, category="Item"),
        "Demon Baby"                         : ItemData(0x27BC86D2, ItemClassification.filler, category="Item"),
        "Forget Me Now"                      : ItemData(0x27BC86D3, ItemClassification.filler, category="Item"),
        "The D20"                            : ItemData(0x27BC86D4, ItemClassification.filler, category="Item"),
        "Celtic Cross"                       : ItemData(0x27BC86D5, ItemClassification.filler, category="Item"),
        "Abel"                               : ItemData(0x27BC86D6, ItemClassification.filler, category="Item"),
        "Curved Horn"                        : ItemData(0x27BC86D7, ItemClassification.filler, category="Item"),
        "Sacrificial Knife"                  : ItemData(0x27BC86D8, ItemClassification.filler, category="Item"),
        "Bloody Lust"                        : ItemData(0x27BC86D9, ItemClassification.filler, category="Item"),
        "Bloody Penny"                       : ItemData(0x27BC86DA, ItemClassification.filler, category="Item"),
        "Blood Rights"                       : ItemData(0x27BC86DB, ItemClassification.filler, category="Item"),
        "The Polaroid"                       : ItemData(0x27BC86DC, ItemClassification.progression, category="Item"),
        "Dad's Key"                          : ItemData(0x27BC86DD, ItemClassification.filler, category="Item"),
        "Blue Candle"                        : ItemData(0x27BC86DE, ItemClassification.filler, category="Item"),
        "Burnt Penny"                        : ItemData(0x27BC86DF, ItemClassification.filler, category="Trinket"),
        "Lucky Toe"                          : ItemData(0x27BC86E0, ItemClassification.filler, category="Trinket"),
        "Epic Fetus"                         : ItemData(0x27BC86E1, ItemClassification.filler, category="Item"),
        "SMB Super Fan"                      : ItemData(0x27BC86E2, ItemClassification.filler, category="Item"),
        "Counterfeit Coin"                   : ItemData(0x27BC86E3, ItemClassification.filler, category="Trinket"),
        "Guppy's Hairball"                   : ItemData(0x27BC86E4, ItemClassification.filler, category="Item"),
        "A Forgotten Horseman"               : ItemData(0x27BC86E5, ItemClassification.progression),
        "Samson"                             : ItemData(0x27BC86E6, ItemClassification.progression, category="Character"),
        "Something Icky"                     : ItemData(0x27BC86E7, ItemClassification.useful),
    #    "!Platinum God!"                    : ItemData(0x27BC86E8, ItemClassification.useful),
        "Isaac's Head"                       : ItemData(0x27BC86E9, ItemClassification.filler, category="Trinket"),
        "Maggy's Faith"                      : ItemData(0x27BC86EA, ItemClassification.filler, category="Trinket"),
        "Judas' Tongue"                      : ItemData(0x27BC86EB, ItemClassification.filler, category="Trinket"),
        "???'s Soul"                         : ItemData(0x27BC86EC, ItemClassification.filler, category="Trinket"),
        "Samson's Lock"                      : ItemData(0x27BC86ED, ItemClassification.filler, category="Trinket"),
        "Cain's Eye"                         : ItemData(0x27BC86EE, ItemClassification.filler, category="Trinket"),
        "Eve's Bird Foot"                    : ItemData(0x27BC86EF, ItemClassification.filler, category="Trinket"),
        "The Left Hand"                      : ItemData(0x27BC86F0, ItemClassification.filler, category="Trinket"),
        "The Negative"                       : ItemData(0x27BC86F1, ItemClassification.progression, category="Item"),
        "Azazel"                             : ItemData(0x27BC86F2, ItemClassification.progression, category="Character"),
        "Lazarus"                            : ItemData(0x27BC86F3, ItemClassification.progression, category="Character"),
        "Eden"                               : ItemData(0x27BC86F4, ItemClassification.progression, category="Character"),
        "Lost"                               : ItemData(0x27BC86F5, ItemClassification.progression, category="Character"),
    #    "Dead Boy"                          : ItemData(0x27BC86F6, ItemClassification.useful),
    #    "Real Platinum God"                 : ItemData(0x27BC86F7, ItemClassification.useful),
        "Lucky Rock"                         : ItemData(0x27BC86F8, ItemClassification.filler, category="Trinket"),
        "Cellar"                             : ItemData(0x27BC86F9, ItemClassification.progression, category="Stage"),
        "Catacombs"                          : ItemData(0x27BC86FA, ItemClassification.progression, category="Stage"),
        "Necropolis"                         : ItemData(0x27BC86FB, ItemClassification.progression, category="Stage"),
        "Rune of Hagalaz"                    : ItemData(0x27BC86FC, ItemClassification.useful),
        "Rune of Jera"                       : ItemData(0x27BC86FD, ItemClassification.useful),
        "Rune of Ehwaz"                      : ItemData(0x27BC86FE, ItemClassification.useful),
        "Rune of Dagaz"                      : ItemData(0x27BC86FF, ItemClassification.useful),
        "Rune of Ansuz"                      : ItemData(0x27BC8700, ItemClassification.useful),
        "Rune of Perthro"                    : ItemData(0x27BC8701, ItemClassification.useful),
        "Rune of Berkano"                    : ItemData(0x27BC8702, ItemClassification.useful),
        "Rune of Algiz"                      : ItemData(0x27BC8703, ItemClassification.useful),
        "Chaos Card"                         : ItemData(0x27BC8704, ItemClassification.useful),
        "Credit Card"                        : ItemData(0x27BC8705, ItemClassification.useful),
        "Rules Card"                         : ItemData(0x27BC8706, ItemClassification.filler),
        "A Card Against Humanity"            : ItemData(0x27BC8707, ItemClassification.useful),
        "Swallowed Penny"                    : ItemData(0x27BC8708, ItemClassification.filler, category="Trinket"),
        "Robo Baby 2.0"                      : ItemData(0x27BC8709, ItemClassification.filler, category="Item"),
        "Death's Touch"                      : ItemData(0x27BC870A, ItemClassification.filler, category="Item"),
        "Technology .5"                      : ItemData(0x27BC870B, ItemClassification.filler, category="Item"),
        "Missing No."                        : ItemData(0x27BC870C, ItemClassification.filler, category="Item"),
        "Isaac's Tears"                      : ItemData(0x27BC870D, ItemClassification.filler, category="Item"),
        "Guillotine"                         : ItemData(0x27BC870E, ItemClassification.filler, category="Item"),
        "Judas' Shadow"                      : ItemData(0x27BC870F, ItemClassification.filler, category="Item"),
        "Maggy's Bow"                        : ItemData(0x27BC8710, ItemClassification.filler, category="Item"),
        "Cain's Other Eye"                   : ItemData(0x27BC8711, ItemClassification.filler, category="Item"),
        "Black Lipstick"                     : ItemData(0x27BC8712, ItemClassification.filler, category="Trinket"),
        "Eve's Mascara"                      : ItemData(0x27BC8713, ItemClassification.filler, category="Item"),
        "Fate"                               : ItemData(0x27BC8714, ItemClassification.filler, category="Item"),
        "???'s Only Friend"                  : ItemData(0x27BC8715, ItemClassification.filler, category="Item"),
        "Samson's Chains"                    : ItemData(0x27BC8716, ItemClassification.filler, category="Item"),
        "Lazarus' Rags"                      : ItemData(0x27BC8717, ItemClassification.filler, category="Item"),
        "Broken Ankh"                        : ItemData(0x27BC8718, ItemClassification.filler, category="Trinket"),
        "Store Credit"                       : ItemData(0x27BC8719, ItemClassification.filler, category="Trinket"),
        "Pandora's Box"                      : ItemData(0x27BC871A, ItemClassification.progression, category="Item"),
        "Suicide King"                       : ItemData(0x27BC871B, ItemClassification.useful),
        "Blank Card"                         : ItemData(0x27BC871C, ItemClassification.progression, category="Item"),
        "Book of Secrets"                    : ItemData(0x27BC871D, ItemClassification.filler, category="Item"),
        "Mysterious Paper"                   : ItemData(0x27BC871E, ItemClassification.filler, category="Trinket"),
        "Mystery Sack"                       : ItemData(0x27BC871F, ItemClassification.filler, category="Item"),
        "Undefined"                          : ItemData(0x27BC8720, ItemClassification.filler, category="Item"),
        "Satanic Bible"                      : ItemData(0x27BC8721, ItemClassification.filler, category="Item"),
        "Daemon Tail"                        : ItemData(0x27BC8722, ItemClassification.filler, category="Trinket"),
        "Abaddon"                            : ItemData(0x27BC8723, ItemClassification.filler, category="Item"),
        "Isaac's Heart"                      : ItemData(0x27BC8724, ItemClassification.filler, category="Item"),
        "The Mind"                           : ItemData(0x27BC8725, ItemClassification.filler, category="Item"),
        "The Body"                           : ItemData(0x27BC8726, ItemClassification.filler, category="Item"),
        "The Soul"                           : ItemData(0x27BC8727, ItemClassification.filler, category="Item"),
        "The D100"                           : ItemData(0x27BC8728, ItemClassification.filler, category="Item"),
        "Blue Map"                           : ItemData(0x27BC8729, ItemClassification.filler, category="Item"),
        "There's Options"                    : ItemData(0x27BC872A, ItemClassification.filler, category="Item"),
        "Black Candle"                       : ItemData(0x27BC872B, ItemClassification.filler, category="Item"),
        "Red Candle"                         : ItemData(0x27BC872C, ItemClassification.filler, category="Item"),
        "Stop Watch"                         : ItemData(0x27BC872D, ItemClassification.progression, category="Item"),
        "Wire Coat Hanger"                   : ItemData(0x27BC872E, ItemClassification.filler, category="Item"),
        "Ipecac"                             : ItemData(0x27BC872F, ItemClassification.progression, category="Item"),
        "Experimental Treatment"             : ItemData(0x27BC8730, ItemClassification.filler, category="Item"),
        "Krampus"                            : ItemData(0x27BC8731, ItemClassification.progression),
        "Head of Krampus"                    : ItemData(0x27BC8732, ItemClassification.filler, category="Item"),
    #    "Super Meat Boy"                    : ItemData(0x27BC8733, ItemClassification.useful),
        "Butter Bean"                        : ItemData(0x27BC8734, ItemClassification.filler, category="Item"),
        "Little Baggy"                       : ItemData(0x27BC8735, ItemClassification.filler, category="Item"),
        "Blood Bag"                          : ItemData(0x27BC8736, ItemClassification.filler, category="Item"),
        "The D4"                             : ItemData(0x27BC8737, ItemClassification.filler, category="Item"),
        "Missing Poster"                     : ItemData(0x27BC8738, ItemClassification.progression, category="Trinket"),
        "Rubber Cement"                      : ItemData(0x27BC8739, ItemClassification.progression, category="Item"),
        "Angels"                             : ItemData(0x27BC873A, ItemClassification.progression, category="Stage"),
        "Godhead"                            : ItemData(0x27BC873B, ItemClassification.filler, category="Item"),
        "Darkness Falls"                     : ItemData(0x27BC873C, ItemClassification.progression, category="Challenge"),
        "The Tank"                           : ItemData(0x27BC873D, ItemClassification.progression, category="Challenge"),
        "Solar System"                       : ItemData(0x27BC873E, ItemClassification.progression, category="Challenge"),
        "Suicide King (Challenge)"           : ItemData(0x27BC873F, ItemClassification.progression, category="Challenge"),
        "Cat Got Your Tongue"                : ItemData(0x27BC8740, ItemClassification.progression, category="Challenge"),
        "Demo Man"                           : ItemData(0x27BC8741, ItemClassification.progression, category="Challenge"),
        "Cursed!"                            : ItemData(0x27BC8742, ItemClassification.progression, category="Challenge"),
        "Glass Cannon"                       : ItemData(0x27BC8743, ItemClassification.progression, category="Challenge"),
        "The Family Man"                     : ItemData(0x27BC8744, ItemClassification.progression, category="Challenge"),
        "Purist"                             : ItemData(0x27BC8745, ItemClassification.progression, category="Challenge"),
        "Lost Baby"                          : ItemData(0x27BC8746, ItemClassification.filler, category="Co-Op Baby"),
        "Cute Baby"                          : ItemData(0x27BC8747, ItemClassification.filler, category="Co-Op Baby"),
        "Crow Baby"                          : ItemData(0x27BC8748, ItemClassification.filler, category="Co-Op Baby"),
        "Shadow Baby"                        : ItemData(0x27BC8749, ItemClassification.filler, category="Co-Op Baby"),
        "Glass Baby"                         : ItemData(0x27BC874A, ItemClassification.filler, category="Co-Op Baby"),
        "Wrapped Baby"                       : ItemData(0x27BC874B, ItemClassification.filler, category="Co-Op Baby"),
        "Begotten Baby"                      : ItemData(0x27BC874C, ItemClassification.filler, category="Co-Op Baby"),
        "Dead Baby"                          : ItemData(0x27BC874D, ItemClassification.filler, category="Co-Op Baby"),
        "-0- Baby"                           : ItemData(0x27BC874E, ItemClassification.filler, category="Co-Op Baby"),
        "Glitch Baby"                        : ItemData(0x27BC874F, ItemClassification.filler, category="Co-Op Baby"),
        "Fighting Baby"                      : ItemData(0x27BC8750, ItemClassification.filler, category="Co-Op Baby"),
    #    "Lord of the Flies"                 : ItemData(0x27BC8751, ItemClassification.useful),
        "Fart Baby"                          : ItemData(0x27BC8752, ItemClassification.filler, category="Item"),
        "Purity"                             : ItemData(0x27BC8753, ItemClassification.filler, category="Item"),
        "D12"                                : ItemData(0x27BC8754, ItemClassification.filler, category="Item"),
        "Betrayal"                           : ItemData(0x27BC8755, ItemClassification.filler, category="Item"),
        "Fate's Reward"                      : ItemData(0x27BC8756, ItemClassification.filler, category="Item"),
        "Athame"                             : ItemData(0x27BC8757, ItemClassification.filler, category="Item"),
        "Blind Rage"                         : ItemData(0x27BC8758, ItemClassification.filler, category="Trinket"),
        "Maw of the Void"                    : ItemData(0x27BC8759, ItemClassification.filler, category="Item"),
        "Empty Vessel"                       : ItemData(0x27BC875A, ItemClassification.filler, category="Item"),
        "Eden's Blessing"                    : ItemData(0x27BC875B, ItemClassification.filler, category="Item"),
        "Sworn Protector"                    : ItemData(0x27BC875C, ItemClassification.filler, category="Item"),
        "Incubus"                            : ItemData(0x27BC875D, ItemClassification.filler, category="Item"),
        "Keeper's Penny"                     : ItemData(0x27BC875E, ItemClassification.filler, category="Item"),
        "Lil' Chest"                         : ItemData(0x27BC875F, ItemClassification.filler, category="Item"),
        "Censer"                             : ItemData(0x27BC8760, ItemClassification.filler, category="Item"),
        "Evil Eye"                           : ItemData(0x27BC8761, ItemClassification.filler, category="Item"),
        "My Shadow"                          : ItemData(0x27BC8762, ItemClassification.filler, category="Item"),
        "Cracked Dice"                       : ItemData(0x27BC8763, ItemClassification.filler, category="Trinket"),
        "Black Feather"                      : ItemData(0x27BC8764, ItemClassification.filler, category="Trinket"),
        "Lusty Blood"                        : ItemData(0x27BC8765, ItemClassification.filler, category="Item"),
        "Lilith"                             : ItemData(0x27BC8766, ItemClassification.progression, category="Character"),
        "Key Bum"                            : ItemData(0x27BC8767, ItemClassification.useful),
        "GB Bug"                             : ItemData(0x27BC8768, ItemClassification.filler, category="Item"),
        "Zodiac"                             : ItemData(0x27BC8769, ItemClassification.filler, category="Item"),
        "Box of Friends"                     : ItemData(0x27BC876A, ItemClassification.filler, category="Item"),
        "Rib of Greed"                       : ItemData(0x27BC876B, ItemClassification.filler, category="Trinket"),
        "Cry Baby"                           : ItemData(0x27BC876C, ItemClassification.filler, category="Co-Op Baby"),
        "Red Baby"                           : ItemData(0x27BC876D, ItemClassification.filler, category="Co-Op Baby"),
        "Green Baby"                         : ItemData(0x27BC876E, ItemClassification.filler, category="Co-Op Baby"),
        "Brown Baby"                         : ItemData(0x27BC876F, ItemClassification.filler, category="Co-Op Baby"),
        "Blue Baby"                          : ItemData(0x27BC8770, ItemClassification.filler, category="Co-Op Baby"),
        "Lil' Baby"                          : ItemData(0x27BC8771, ItemClassification.filler, category="Co-Op Baby"),
        "Rage Baby"                          : ItemData(0x27BC8772, ItemClassification.filler, category="Co-Op Baby"),
        "Black Baby"                         : ItemData(0x27BC8773, ItemClassification.filler, category="Co-Op Baby"),
        "Long Baby"                          : ItemData(0x27BC8774, ItemClassification.filler, category="Co-Op Baby"),
        "Yellow Baby"                        : ItemData(0x27BC8775, ItemClassification.filler, category="Co-Op Baby"),
        "White Baby"                         : ItemData(0x27BC8776, ItemClassification.filler, category="Co-Op Baby"),
        "Big Baby"                           : ItemData(0x27BC8777, ItemClassification.filler, category="Co-Op Baby"),
        "Noose Baby"                         : ItemData(0x27BC8778, ItemClassification.filler, category="Co-Op Baby"),
        "Rune Bag"                           : ItemData(0x27BC8779, ItemClassification.filler, category="Item"),
        "Cambion Conception"                 : ItemData(0x27BC877A, ItemClassification.filler, category="Item"),
        "Serpent's Kiss"                     : ItemData(0x27BC877B, ItemClassification.filler, category="Item"),
        "Succubus"                           : ItemData(0x27BC877C, ItemClassification.filler, category="Item"),
        "Immaculate Conception"              : ItemData(0x27BC877D, ItemClassification.filler, category="Item"),
        "Goat Head Baby"                     : ItemData(0x27BC877E, ItemClassification.filler, category="Co-Op Baby"),
        "Gold Heart"                         : ItemData(0x27BC877F, ItemClassification.useful),
        "Get out of Jail Free Card"          : ItemData(0x27BC8780, ItemClassification.useful),
        "Gold Bomb"                          : ItemData(0x27BC8781, ItemClassification.useful),
        "Percs and Addicted"                 : ItemData(0x27BC8782, ItemClassification.useful),
        "Re-Lax and ???"                     : ItemData(0x27BC8783, ItemClassification.useful),
        "Poker Chip"                         : ItemData(0x27BC8784, ItemClassification.filler, category="Trinket"),
        "Stud Finder"                        : ItemData(0x27BC8785, ItemClassification.filler, category="Trinket"),
        "D8"                                 : ItemData(0x27BC8786, ItemClassification.filler, category="Item"),
        "Kidney Stone"                       : ItemData(0x27BC8787, ItemClassification.filler, category="Item"),
        "Blank Rune"                         : ItemData(0x27BC8788, ItemClassification.filler, category="Item"),
        "Blue Womb"                          : ItemData(0x27BC8789, ItemClassification.progression, category="Stage"),
    #    "1001%"                             : ItemData(0x27BC878A, ItemClassification.useful),
        "Keeper's Wooden Nickel"             : ItemData(0x27BC878B, ItemClassification.useful),
        "Keeper's Store Key"                 : ItemData(0x27BC878C, ItemClassification.useful),
        "Deep Pockets"                       : ItemData(0x27BC878D, ItemClassification.filler, category="Item"),
        "Karma"                              : ItemData(0x27BC878E, ItemClassification.filler, category="Trinket"),
        "Sticky Nickels"                     : ItemData(0x27BC878F, ItemClassification.trap),
        "Super Greed Baby"                   : ItemData(0x27BC8790, ItemClassification.filler, category="Co-Op Baby"),
        "Lucky Pennies"                      : ItemData(0x27BC8791, ItemClassification.useful),
        "Special Hanging Shopkeepers"        : ItemData(0x27BC8792, ItemClassification.useful),
        "Wooden Nickel"                      : ItemData(0x27BC8793, ItemClassification.filler, category="Item"),
        "Paperclip"                          : ItemData(0x27BC8794, ItemClassification.filler, category="Trinket"),
        "Everything is Terrible 2!!!"        : ItemData(0x27BC8795, ItemClassification.trap),
        "Special Shopkeepers"                : ItemData(0x27BC8796, ItemClassification.useful),
        "Razor Blade"                        : ItemData(0x27BC8797, ItemClassification.useful),
        "Store Key"                          : ItemData(0x27BC8798, ItemClassification.filler, category="Trinket"),
        "Lost's Holy Mantle"                 : ItemData(0x27BC8799, ItemClassification.progression, category="Character"),
        "Keeper"                             : ItemData(0x27BC879A, ItemClassification.progression, category="Character"),
        "Hive Baby"                          : ItemData(0x27BC879B, ItemClassification.filler, category="Co-Op Baby"),
        "Buddy Baby"                         : ItemData(0x27BC879C, ItemClassification.filler, category="Co-Op Baby"),
        "Colorful Baby"                      : ItemData(0x27BC879D, ItemClassification.filler, category="Co-Op Baby"),
        "Whore Baby"                         : ItemData(0x27BC879E, ItemClassification.filler, category="Co-Op Baby"),
        "Cracked Baby"                       : ItemData(0x27BC879F, ItemClassification.filler, category="Co-Op Baby"),
        "Dripping Baby"                      : ItemData(0x27BC87A0, ItemClassification.filler, category="Co-Op Baby"),
        "Blinding Baby"                      : ItemData(0x27BC87A1, ItemClassification.filler, category="Co-Op Baby"),
        "Sucky Baby"                         : ItemData(0x27BC87A2, ItemClassification.filler, category="Co-Op Baby"),
        "Dark Baby"                          : ItemData(0x27BC87A3, ItemClassification.filler, category="Co-Op Baby"),
        "Picky Baby"                         : ItemData(0x27BC87A4, ItemClassification.filler, category="Co-Op Baby"),
        "Revenge Baby"                       : ItemData(0x27BC87A5, ItemClassification.filler, category="Co-Op Baby"),
        "Belial Baby"                        : ItemData(0x27BC87A6, ItemClassification.filler, category="Co-Op Baby"),
        "Sale Baby"                          : ItemData(0x27BC87A7, ItemClassification.filler, category="Co-Op Baby"),
        "XXXXXXXXL"                          : ItemData(0x27BC87A8, ItemClassification.progression, category="Challenge"),
        "SPEED!"                             : ItemData(0x27BC87A9, ItemClassification.progression, category="Challenge"),
        "Blue Bomber"                        : ItemData(0x27BC87AA, ItemClassification.progression, category="Challenge"),
        "PAY TO PLAY"                        : ItemData(0x27BC87AB, ItemClassification.progression, category="Challenge"),
        "Have a heart"                       : ItemData(0x27BC87AC, ItemClassification.progression, category="Challenge"),
        "I RULE!"                            : ItemData(0x27BC87AD, ItemClassification.progression, category="Challenge"),
        "BRAINS!"                            : ItemData(0x27BC87AE, ItemClassification.progression, category="Challenge"),
        "PRIDE DAY!"                         : ItemData(0x27BC87AF, ItemClassification.progression, category="Challenge"),
        "Onan's Streak"                      : ItemData(0x27BC87B0, ItemClassification.progression, category="Challenge"),
        "The Guardian"                       : ItemData(0x27BC87B1, ItemClassification.progression, category="Challenge"),
        "Generosity"                         : ItemData(0x27BC87B2, ItemClassification.filler),
        "Mega Blast"                         : ItemData(0x27BC87B3, ItemClassification.filler, category="Item"),
        "Backasswards"                       : ItemData(0x27BC87B4, ItemClassification.progression, category="Challenge"),
        "Aprils fool"                        : ItemData(0x27BC87B5, ItemClassification.progression, category="Challenge"),
        "Pokey mans"                         : ItemData(0x27BC87B6, ItemClassification.progression, category="Challenge"),
        "Ultra hard"                         : ItemData(0x27BC87B7, ItemClassification.progression, category="Challenge"),
        "PONG"                               : ItemData(0x27BC87B8, ItemClassification.progression, category="Challenge"),
        "D infinity"                         : ItemData(0x27BC87B9, ItemClassification.filler, category="Item"),
        "Eucharist"                          : ItemData(0x27BC87BA, ItemClassification.filler, category="Item"),
        "Silver Dollar"                      : ItemData(0x27BC87BB, ItemClassification.filler, category="Trinket"),
        "Shade"                              : ItemData(0x27BC87BC, ItemClassification.filler, category="Item"),
        "King Baby"                          : ItemData(0x27BC87BD, ItemClassification.filler, category="Item"),
        "Bloody Crown"                       : ItemData(0x27BC87BE, ItemClassification.filler, category="Trinket"),
        "Dull Razor"                         : ItemData(0x27BC87BF, ItemClassification.filler, category="Item"),
        "Eden's Soul"                        : ItemData(0x27BC87C0, ItemClassification.filler, category="Item"),
        "Dark Prince's Crown"                : ItemData(0x27BC87C1, ItemClassification.filler, category="Item"),
        "Compound Fracture"                  : ItemData(0x27BC87C2, ItemClassification.filler, category="Item"),
        "Euthanasia"                         : ItemData(0x27BC87C3, ItemClassification.filler, category="Item"),
        "Holy Card"                          : ItemData(0x27BC87C4, ItemClassification.progression),
        "Crooked Penny"                      : ItemData(0x27BC87C5, ItemClassification.filler, category="Item"),
        "Void"                               : ItemData(0x27BC87C6, ItemClassification.filler, category="Item"),
        "D1"                                 : ItemData(0x27BC87C7, ItemClassification.filler, category="Item"),
        "Glyph of Balance"                   : ItemData(0x27BC87C8, ItemClassification.filler, category="Item"),
        "Sack of Sacks"                      : ItemData(0x27BC87C9, ItemClassification.filler, category="Item"),
        "Eye of Belial"                      : ItemData(0x27BC87CA, ItemClassification.filler, category="Item"),
        "Meconium"                           : ItemData(0x27BC87CB, ItemClassification.filler, category="Trinket"),
        "Stem Cell"                          : ItemData(0x27BC87CC, ItemClassification.filler, category="Trinket"),
        "Crow Heart"                         : ItemData(0x27BC87CD, ItemClassification.filler, category="Trinket"),
        "Metronome"                          : ItemData(0x27BC87CE, ItemClassification.filler, category="Item"),
        "Bat Wing"                           : ItemData(0x27BC87CF, ItemClassification.filler, category="Trinket"),
        "Plan C"                             : ItemData(0x27BC87D0, ItemClassification.filler, category="Item"),
        "Duality"                            : ItemData(0x27BC87D1, ItemClassification.filler, category="Item"),
        "Dad's Lost Coin"                    : ItemData(0x27BC87D2, ItemClassification.filler, category="Item"),
        "Eye of Greed"                       : ItemData(0x27BC87D3, ItemClassification.filler, category="Item"),
        "Black Rune"                         : ItemData(0x27BC87D4, ItemClassification.useful),
        "Locust of Wrath"                    : ItemData(0x27BC87D5, ItemClassification.filler, category="Trinket"),
        "Locust of Pestilence"               : ItemData(0x27BC87D6, ItemClassification.filler, category="Trinket"),
        "Locust of Famine"                   : ItemData(0x27BC87D7, ItemClassification.filler, category="Trinket"),
        "Locust of Death"                    : ItemData(0x27BC87D8, ItemClassification.filler, category="Trinket"),
        "Locust of Conquest"                 : ItemData(0x27BC87D9, ItemClassification.filler, category="Trinket"),
        "Hushy"                              : ItemData(0x27BC87DA, ItemClassification.filler, category="Item"),
        "Brown Nugget"                       : ItemData(0x27BC87DB, ItemClassification.filler, category="Item"),
        "Mort Baby"                          : ItemData(0x27BC87DC, ItemClassification.filler, category="Co-Op Baby"),
        "Smelter"                            : ItemData(0x27BC87DD, ItemClassification.filler, category="Item"),
        "Apollyon Baby"                      : ItemData(0x27BC87DE, ItemClassification.filler, category="Co-Op Baby"),
        "The Void"                           : ItemData(0x27BC87DF, ItemClassification.progression, category="Stage"),
        "Gulp!"                              : ItemData(0x27BC87E0, ItemClassification.progression),
        "Ace of Clubs"                       : ItemData(0x27BC87E1, ItemClassification.useful),
        "Super Tinted Rocks"                 : ItemData(0x27BC87E2, ItemClassification.useful),
        "Feels Like I'm Walking on Sunshine!": ItemData(0x27BC87E3, ItemClassification.useful),
        "Horf!"                              : ItemData(0x27BC87E4, ItemClassification.useful),
        "Ace of Diamonds"                    : ItemData(0x27BC87E5, ItemClassification.useful),
        "Ace of Spades"                      : ItemData(0x27BC87E6, ItemClassification.useful),
        "Scared Hearts"                      : ItemData(0x27BC87E7, ItemClassification.trap),
        "Living on the edge"                 : ItemData(0x27BC87E8, ItemClassification.useful),
        "Vurp!"                              : ItemData(0x27BC87E9, ItemClassification.useful),
        "Laz Bleeds More!"                   : ItemData(0x27BC87EA, ItemClassification.useful),
        "Maggy now hold a pill!"             : ItemData(0x27BC87EB, ItemClassification.useful),
        "Charged Key"                        : ItemData(0x27BC87EC, ItemClassification.useful),
        "Samson feels healthy!"              : ItemData(0x27BC87ED, ItemClassification.useful),
        "Greed's Gullet"                     : ItemData(0x27BC87EE, ItemClassification.filler, category="Item"),
#        "The Marathon"                       : ItemData(0x27BC87EF, ItemClassification.useful),
        "RERUN"                              : ItemData(0x27BC87F0, ItemClassification.useful),
        "Delirious"                          : ItemData(0x27BC87F1, ItemClassification.filler, category="Item"),
#        "1000000%"                           : ItemData(0x27BC87F2, ItemClassification.useful),
        "Apollyon"                           : ItemData(0x27BC87F3, ItemClassification.progression, category="Character"),
        "Greedier!"                          : ItemData(0x27BC87F4, ItemClassification.progression, category="Stage"),
        "Burning Basement"                   : ItemData(0x27BC87F5, ItemClassification.progression, category="Stage"),
        "Flooded Caves"                      : ItemData(0x27BC87F6, ItemClassification.progression, category="Stage"),
        "Dank Depths"                        : ItemData(0x27BC87F7, ItemClassification.progression, category="Stage"),
        "Scarred Womb"                       : ItemData(0x27BC87F8, ItemClassification.progression, category="Stage"),
        "Something wicked this way comes!"   : ItemData(0x27BC87F9, ItemClassification.useful),
        "Something wicked this way comes+!"  : ItemData(0x27BC87FA, ItemClassification.useful),
        "The gate is open!"                  : ItemData(0x27BC87FB, ItemClassification.progression),
        "Black Hole"                         : ItemData(0x27BC87FC, ItemClassification.filler, category="Item"),
        "Mystery Gift"                       : ItemData(0x27BC87FD, ItemClassification.filler, category="Item"),
        "Sprinkler"                          : ItemData(0x27BC87FE, ItemClassification.filler, category="Item"),
        "Angry Fly"                          : ItemData(0x27BC87FF, ItemClassification.filler, category="Item"),
        "Bozo"                               : ItemData(0x27BC8800, ItemClassification.filler, category="Item"),
        "Broken Modem"                       : ItemData(0x27BC8801, ItemClassification.filler, category="Item"),
        "Buddy in a Box"                     : ItemData(0x27BC8802, ItemClassification.filler, category="Item"),
        "Fast Bombs"                         : ItemData(0x27BC8803, ItemClassification.filler, category="Item"),
        "Lil Delirium"                       : ItemData(0x27BC8804, ItemClassification.filler, category="Item"),
        "Hairpin"                            : ItemData(0x27BC8805, ItemClassification.filler, category="Trinket"),
        "Wooden Cross"                       : ItemData(0x27BC8806, ItemClassification.filler, category="Trinket"),
        "Butter"                             : ItemData(0x27BC8807, ItemClassification.filler, category="Trinket"),
        "Huge Growth"                        : ItemData(0x27BC8808, ItemClassification.useful),
        "Ancient Recall"                     : ItemData(0x27BC8809, ItemClassification.useful),
        "Era Walk"                           : ItemData(0x27BC880A, ItemClassification.useful),
        "Coupon"                             : ItemData(0x27BC880B, ItemClassification.filler, category="Item"),
        "Telekinesis"                        : ItemData(0x27BC880C, ItemClassification.filler, category="Item"),
        "Moving Box"                         : ItemData(0x27BC880D, ItemClassification.filler, category="Item"),
        "Jumper Cables"                      : ItemData(0x27BC880E, ItemClassification.filler, category="Item"),
        "Leprosy"                            : ItemData(0x27BC880F, ItemClassification.filler, category="Item"),
        "Technology Zero"                    : ItemData(0x27BC8810, ItemClassification.filler, category="Item"),
        "Filigree Feather"                   : ItemData(0x27BC8811, ItemClassification.filler, category="Trinket"),
        "Mr. Me"                             : ItemData(0x27BC8812, ItemClassification.filler, category="Item"),
        "7 Seals"                            : ItemData(0x27BC8813, ItemClassification.filler, category="Item"),
        "Angelic Prism"                      : ItemData(0x27BC8814, ItemClassification.filler, category="Item"),
        "Pop!"                               : ItemData(0x27BC8815, ItemClassification.filler, category="Item"),
        "Door Stop"                          : ItemData(0x27BC8816, ItemClassification.filler, category="Trinket"),
        "Death's List"                       : ItemData(0x27BC8817, ItemClassification.filler, category="Item"),
        "Haemolacria"                        : ItemData(0x27BC8818, ItemClassification.filler, category="Item"),
        "Lachryphagy"                        : ItemData(0x27BC8819, ItemClassification.filler, category="Item"),
        "Schoolbag"                          : ItemData(0x27BC881A, ItemClassification.filler, category="Item"),
        "Trisagion"                          : ItemData(0x27BC881B, ItemClassification.filler, category="Item"),
        "Extension Cord"                     : ItemData(0x27BC881C, ItemClassification.filler, category="Trinket"),
        "Flat Stone"                         : ItemData(0x27BC881D, ItemClassification.filler, category="Item"),
        "Sacrificial Altar"                  : ItemData(0x27BC881E, ItemClassification.filler, category="Item"),
        "Lil Spewer"                         : ItemData(0x27BC881F, ItemClassification.filler, category="Item"),
        "Blanket"                            : ItemData(0x27BC8820, ItemClassification.filler, category="Item"),
        "Marbles"                            : ItemData(0x27BC8821, ItemClassification.filler, category="Item"),
        "Mystery Egg"                        : ItemData(0x27BC8822, ItemClassification.filler, category="Item"),
        "Rotten Penny"                       : ItemData(0x27BC8823, ItemClassification.filler, category="Trinket"),
        "Baby-Bender"                        : ItemData(0x27BC8824, ItemClassification.filler, category="Trinket"),
        "Forgotten"                          : ItemData(0x27BC8825, ItemClassification.progression, category="Character"),
        "Bone Heart"                         : ItemData(0x27BC8826, ItemClassification.useful),
        "Marrow"                             : ItemData(0x27BC8827, ItemClassification.filler, category="Item"),
        "Slipped Rib"                        : ItemData(0x27BC8828, ItemClassification.filler, category="Item"),
        "Pointy Rib"                         : ItemData(0x27BC8829, ItemClassification.filler, category="Item"),
        "Jaw Bone"                           : ItemData(0x27BC882A, ItemClassification.filler, category="Item"),
        "Brittle Bones"                      : ItemData(0x27BC882B, ItemClassification.filler, category="Item"),
        "Divorce Papers"                     : ItemData(0x27BC882C, ItemClassification.filler, category="Item"),
        "Hallowed Ground"                    : ItemData(0x27BC882D, ItemClassification.filler, category="Item"),
        "Finger Bone"                        : ItemData(0x27BC882E, ItemClassification.filler, category="Trinket"),
        "Dad's Ring"                         : ItemData(0x27BC882F, ItemClassification.filler, category="Item"),
        "Book of the Dead"                   : ItemData(0x27BC8830, ItemClassification.filler, category="Item"),
        "Bone Baby"                          : ItemData(0x27BC8831, ItemClassification.filler, category="Co-Op Baby"),
        "Bound Baby"                         : ItemData(0x27BC8832, ItemClassification.filler, category="Co-Op Baby"),
        "Bethany"                            : ItemData(0x27BC8833, ItemClassification.progression, category="Character"),
        "Jacob and Esau"                     : ItemData(0x27BC8834, ItemClassification.progression, category="Character"),
        "The Planetarium"                    : ItemData(0x27BC8835, ItemClassification.progression, category="Stage"),
        "A Secret Exit"                      : ItemData(0x27BC8836, ItemClassification.progression, category="Stage"),
        "Forgotten Lullaby"                  : ItemData(0x27BC8837, ItemClassification.filler, category="Trinket"),
        "Fruity Plum"                        : ItemData(0x27BC8838, ItemClassification.filler, category="Item"),
        "Plum Flute"                         : ItemData(0x27BC8839, ItemClassification.filler, category="Item"),
        "Rotten Heart"                       : ItemData(0x27BC883A, ItemClassification.useful),
        "Dross"                              : ItemData(0x27BC883B, ItemClassification.progression, category="Stage"),
        "Ashpit"                             : ItemData(0x27BC883C, ItemClassification.progression, category="Stage"),
        "Gehenna"                            : ItemData(0x27BC883D, ItemClassification.progression, category="Stage"),
        "Red Key"                            : ItemData(0x27BC883E, ItemClassification.progression, category="Item"),
        "Wisp Baby"                          : ItemData(0x27BC883F, ItemClassification.filler, category="Co-Op Baby"),
        "Book of Virtues"                    : ItemData(0x27BC8840, ItemClassification.filler, category="Item"),
        "Urn of Souls"                       : ItemData(0x27BC8841, ItemClassification.filler, category="Item"),
        "Blessed Penny"                      : ItemData(0x27BC8842, ItemClassification.filler, category="Trinket"),
        "Alabaster Box"                      : ItemData(0x27BC8843, ItemClassification.filler, category="Item"),
        "Beth's Faith"                       : ItemData(0x27BC8844, ItemClassification.filler, category="Trinket"),
        "Soul Locket"                        : ItemData(0x27BC8845, ItemClassification.filler, category="Item"),
        "Divine Intervention"                : ItemData(0x27BC8846, ItemClassification.filler, category="Item"),
        "Vade Retro"                         : ItemData(0x27BC8847, ItemClassification.filler, category="Item"),
        "Star of Bethlehem"                  : ItemData(0x27BC8848, ItemClassification.filler, category="Item"),
        "Hope Baby"                          : ItemData(0x27BC8849, ItemClassification.filler, category="Co-Op Baby"),
        "Glowing Baby"                       : ItemData(0x27BC884A, ItemClassification.filler, category="Co-Op Baby"),
        "Double Baby"                        : ItemData(0x27BC884B, ItemClassification.filler, category="Co-Op Baby"),
        "The Stairway"                       : ItemData(0x27BC884C, ItemClassification.filler, category="Item"),
        "Red Stew"                           : ItemData(0x27BC884D, ItemClassification.filler, category="Item"),
        "Birthright"                         : ItemData(0x27BC884E, ItemClassification.filler, category="Item"),
        "Damocles"                           : ItemData(0x27BC884F, ItemClassification.filler, category="Item"),
        "Rock Bottom"                        : ItemData(0x27BC8850, ItemClassification.filler, category="Item"),
        "Inner Child"                        : ItemData(0x27BC8851, ItemClassification.filler, category="Item"),
        "Vanishing Twin"                     : ItemData(0x27BC8852, ItemClassification.filler, category="Item"),
        "Genesis"                            : ItemData(0x27BC8853, ItemClassification.filler, category="Item"),
        "Suplex!"                            : ItemData(0x27BC8854, ItemClassification.filler, category="Item"),
        "Solomon's Baby"                     : ItemData(0x27BC8855, ItemClassification.filler, category="Co-Op Baby"),
        "Illusion Baby"                      : ItemData(0x27BC8856, ItemClassification.filler, category="Co-Op Baby"),
        "Meat Cleaver"                       : ItemData(0x27BC8857, ItemClassification.filler, category="Item"),
        "Options?"                           : ItemData(0x27BC8858, ItemClassification.filler, category="Item"),
        "Yuck Heart"                         : ItemData(0x27BC8859, ItemClassification.filler, category="Item"),
        "Candy Heart"                        : ItemData(0x27BC885A, ItemClassification.filler, category="Item"),
        "Guppy's Eye"                        : ItemData(0x27BC885B, ItemClassification.filler, category="Item"),
        "A Pound of Flesh"                   : ItemData(0x27BC885C, ItemClassification.filler, category="Item"),
        "Akeldama"                           : ItemData(0x27BC885D, ItemClassification.filler, category="Item"),
        "Redemption"                         : ItemData(0x27BC885E, ItemClassification.filler, category="Item"),
        "Eternal D6"                         : ItemData(0x27BC885F, ItemClassification.filler, category="Item"),
        "Montezuma's Revenge"                : ItemData(0x27BC8860, ItemClassification.filler, category="Item"),
        "Bird Cage"                          : ItemData(0x27BC8861, ItemClassification.filler, category="Item"),
        "Cracked Orb"                        : ItemData(0x27BC8862, ItemClassification.filler, category="Item"),
        "Bloody Gust"                        : ItemData(0x27BC8863, ItemClassification.filler, category="Item"),
        "Empty Heart"                        : ItemData(0x27BC8864, ItemClassification.filler, category="Item"),
        "Devil's Crown"                      : ItemData(0x27BC8865, ItemClassification.filler, category="Item"),
        "Lil Abaddon"                        : ItemData(0x27BC8866, ItemClassification.filler, category="Item"),
        "Tinytoma"                           : ItemData(0x27BC8867, ItemClassification.filler, category="Item"),
        "Astral Projection"                  : ItemData(0x27BC8868, ItemClassification.filler, category="Item"),
        " 'M"                                : ItemData(0x27BC8869, ItemClassification.filler, category="Trinket"),
        "Everything Jar"                     : ItemData(0x27BC886A, ItemClassification.filler, category="Item"),
        "Lost Soul"                          : ItemData(0x27BC886B, ItemClassification.filler, category="Item"),
        "Hungry Soul"                        : ItemData(0x27BC886C, ItemClassification.filler, category="Item"),
        "Blood Puppy"                        : ItemData(0x27BC886D, ItemClassification.filler, category="Item"),
        "C Section"                          : ItemData(0x27BC886E, ItemClassification.filler, category="Item"),
        "Keeper's Sack"                      : ItemData(0x27BC886F, ItemClassification.filler, category="Item"),
        "Keeper's Box"                       : ItemData(0x27BC8870, ItemClassification.filler, category="Item"),
        "Lil Portal"                         : ItemData(0x27BC8871, ItemClassification.filler, category="Item"),
        "Worm Friend"                        : ItemData(0x27BC8872, ItemClassification.filler, category="Item"),
        "Bone Spurs"                         : ItemData(0x27BC8873, ItemClassification.filler, category="Item"),
        "Spirit Shackles"                    : ItemData(0x27BC8874, ItemClassification.filler, category="Item"),
        "Revelation"                         : ItemData(0x27BC8875, ItemClassification.filler, category="Item"),
        "Jar of Wisps"                       : ItemData(0x27BC8876, ItemClassification.filler, category="Item"),
        "Magic Skin"                         : ItemData(0x27BC8877, ItemClassification.filler, category="Item"),
        "Friend Finder"                      : ItemData(0x27BC8878, ItemClassification.filler, category="Item"),
        "The Broken"                         : ItemData(0x27BC8879, ItemClassification.progression, category="Tainted Character"),
        "The Dauntless"                      : ItemData(0x27BC887A, ItemClassification.progression, category="Tainted Character"),
        "The Hoarder"                        : ItemData(0x27BC887B, ItemClassification.progression, category="Tainted Character"),
        "The Deceiver"                       : ItemData(0x27BC887C, ItemClassification.progression, category="Tainted Character"),
        "The Soiled"                         : ItemData(0x27BC887D, ItemClassification.progression, category="Tainted Character"),
        "The Curdled"                        : ItemData(0x27BC887E, ItemClassification.progression, category="Tainted Character"),
        "The Savage"                         : ItemData(0x27BC887F, ItemClassification.progression, category="Tainted Character"),
        "The Benighted"                      : ItemData(0x27BC8880, ItemClassification.progression, category="Tainted Character"),
        "The Enigma"                         : ItemData(0x27BC8881, ItemClassification.progression, category="Tainted Character"),
        "The Capricious"                     : ItemData(0x27BC8882, ItemClassification.progression, category="Tainted Character"),
        "The Baleful"                        : ItemData(0x27BC8883, ItemClassification.progression, category="Tainted Character"),
        "The Harlot"                         : ItemData(0x27BC8884, ItemClassification.progression, category="Tainted Character"),
        "The Miser"                          : ItemData(0x27BC8885, ItemClassification.progression, category="Tainted Character"),
        "The Empty"                          : ItemData(0x27BC8886, ItemClassification.progression, category="Tainted Character"),
        "The Fettered"                       : ItemData(0x27BC8887, ItemClassification.progression, category="Tainted Character"),
        "The Zealot"                         : ItemData(0x27BC8888, ItemClassification.progression, category="Tainted Character"),
        "The Deserter"                       : ItemData(0x27BC8889, ItemClassification.progression, category="Tainted Character"),
        "Glitched Crown"                     : ItemData(0x27BC888A, ItemClassification.filler, category="Item"),
        "Belly Jelly"                        : ItemData(0x27BC888B, ItemClassification.filler, category="Item"),
        "Blue Key"                           : ItemData(0x27BC888C, ItemClassification.filler, category="Trinket"),
        "Sanguine Bond"                      : ItemData(0x27BC888D, ItemClassification.filler, category="Item"),
        "The Swarm"                          : ItemData(0x27BC888E, ItemClassification.filler, category="Item"),
        "Heartbreak"                         : ItemData(0x27BC888F, ItemClassification.filler, category="Item"),
        "Larynx"                             : ItemData(0x27BC8890, ItemClassification.filler, category="Item"),
        "Azazel's Rage"                      : ItemData(0x27BC8891, ItemClassification.filler, category="Item"),
        "Salvation"                          : ItemData(0x27BC8892, ItemClassification.filler, category="Item"),
        "TMTRAINER"                          : ItemData(0x27BC8893, ItemClassification.filler, category="Item"),
        "Sacred Orb"                         : ItemData(0x27BC8894, ItemClassification.filler, category="Item"),
        "Twisted Pair"                       : ItemData(0x27BC8895, ItemClassification.filler, category="Item"),
        "Strawman"                           : ItemData(0x27BC8896, ItemClassification.filler, category="Item"),
        "Echo Chamber"                       : ItemData(0x27BC8897, ItemClassification.filler, category="Item"),
        "Isaac's Tomb"                       : ItemData(0x27BC8898, ItemClassification.filler, category="Item"),
        "Vengeful Spirit"                    : ItemData(0x27BC8899, ItemClassification.filler, category="Item"),
        "Esau Jr."                           : ItemData(0x27BC889A, ItemClassification.filler, category="Item"),
        "Bloody Mary"                        : ItemData(0x27BC889B, ItemClassification.progression, category="Challenge"),
        "Baptism by Fire"                    : ItemData(0x27BC889C, ItemClassification.progression, category="Challenge"),
        "Isaac's Awakening"                  : ItemData(0x27BC889D, ItemClassification.progression, category="Challenge"),
        "Seeing Double"                      : ItemData(0x27BC889E, ItemClassification.progression, category="Challenge"),
        "Pica Run"                           : ItemData(0x27BC889F, ItemClassification.progression, category="Challenge"),
        "Hot Potato"                         : ItemData(0x27BC88A0, ItemClassification.progression, category="Challenge"),
        "Cantripped!"                        : ItemData(0x27BC88A1, ItemClassification.progression, category="Challenge"),
        "Red Redemption"                     : ItemData(0x27BC88A2, ItemClassification.progression, category="Challenge"),
        "DELETE THIS"                        : ItemData(0x27BC88A3, ItemClassification.progression, category="Challenge"),
        "Dirty Mind"                         : ItemData(0x27BC88A4, ItemClassification.filler, category="Item"),
        "Sigil of Baphomet"                  : ItemData(0x27BC88A5, ItemClassification.filler, category="Item"),
        "Purgatory"                          : ItemData(0x27BC88A6, ItemClassification.filler, category="Item"),
        "Spirit Sword"                       : ItemData(0x27BC88A7, ItemClassification.filler, category="Item"),
        "Broken Glasses"                     : ItemData(0x27BC88A8, ItemClassification.filler, category="Trinket"),
        "Ice Cube"                           : ItemData(0x27BC88A9, ItemClassification.filler, category="Trinket"),
        "Charged Penny"                      : ItemData(0x27BC88AA, ItemClassification.filler, category="Trinket"),
        "The Fool?"                          : ItemData(0x27BC88AB, ItemClassification.useful),
        "The Magician?"                      : ItemData(0x27BC88AC, ItemClassification.useful),
        "The High Priestess?"                : ItemData(0x27BC88AD, ItemClassification.useful),
        "The Empress?"                       : ItemData(0x27BC88AE, ItemClassification.useful),
        "The Emperor?"                       : ItemData(0x27BC88AF, ItemClassification.useful),
        "The Hierophant?"                    : ItemData(0x27BC88B0, ItemClassification.useful),
        "The Lovers?"                        : ItemData(0x27BC88B1, ItemClassification.useful),
        "The Chariot?"                       : ItemData(0x27BC88B2, ItemClassification.useful),
        "Justice?"                           : ItemData(0x27BC88B3, ItemClassification.useful),
        "The Hermit?"                        : ItemData(0x27BC88B4, ItemClassification.useful),
        "Wheel of Fortune?"                  : ItemData(0x27BC88B5, ItemClassification.useful),
        "Strength?"                          : ItemData(0x27BC88B6, ItemClassification.useful),
        "The Hanged Man?"                    : ItemData(0x27BC88B7, ItemClassification.useful),
        "Death?"                             : ItemData(0x27BC88B8, ItemClassification.useful),
        "Temperance?"                        : ItemData(0x27BC88B9, ItemClassification.useful),
        "The Devil?"                         : ItemData(0x27BC88BA, ItemClassification.useful),
        "The Tower?"                         : ItemData(0x27BC88BB, ItemClassification.useful),
        "The Stars?"                         : ItemData(0x27BC88BC, ItemClassification.useful),
        "The Sun? and the Moon?"             : ItemData(0x27BC88BD, ItemClassification.useful),
        "Judgement?"                         : ItemData(0x27BC88BE, ItemClassification.useful),
        "The World?"                         : ItemData(0x27BC88BF, ItemClassification.useful),
        "Old Capacitor"                      : ItemData(0x27BC88C0, ItemClassification.filler, category="Trinket"),
        "Brimstone Bombs"                    : ItemData(0x27BC88C1, ItemClassification.filler, category="Item"),
        "Mega Mush"                          : ItemData(0x27BC88C2, ItemClassification.filler, category="Item"),
        "Mom's Lock"                         : ItemData(0x27BC88C3, ItemClassification.filler, category="Trinket"),
        "Dice Bag"                           : ItemData(0x27BC88C4, ItemClassification.filler, category="Trinket"),
        "Holy Crown"                         : ItemData(0x27BC88C5, ItemClassification.filler, category="Trinket"),
        "Mother's Kiss"                      : ItemData(0x27BC88C6, ItemClassification.filler, category="Trinket"),
        "Gilded Key"                         : ItemData(0x27BC88C7, ItemClassification.filler, category="Trinket"),
        "Lucky Sack"                         : ItemData(0x27BC88C8, ItemClassification.filler, category="Trinket"),
        "Your Soul"                          : ItemData(0x27BC88C9, ItemClassification.filler, category="Trinket"),
        "Number Magnet"                      : ItemData(0x27BC88CA, ItemClassification.filler, category="Trinket"),
        "Dingle Berry"                       : ItemData(0x27BC88CB, ItemClassification.filler, category="Trinket"),
        "Ring Cap"                           : ItemData(0x27BC88CC, ItemClassification.filler, category="Trinket"),
        "Strange Key"                        : ItemData(0x27BC88CD, ItemClassification.filler, category="Trinket"),
        "Lil Clot"                           : ItemData(0x27BC88CE, ItemClassification.filler, category="Trinket"),
        "Temporary Tattoo"                   : ItemData(0x27BC88CF, ItemClassification.filler, category="Trinket"),
        "Swallowed M80"                      : ItemData(0x27BC88D0, ItemClassification.filler, category="Trinket"),
        "Wicked Crown"                       : ItemData(0x27BC88D1, ItemClassification.filler, category="Trinket"),
        "Azazel's Stump"                     : ItemData(0x27BC88D2, ItemClassification.filler, category="Trinket"),
        "Torn Pocket"                        : ItemData(0x27BC88D3, ItemClassification.filler, category="Trinket"),
        "Torn Card"                          : ItemData(0x27BC88D4, ItemClassification.filler, category="Trinket"),
        "Nuh Uh!"                            : ItemData(0x27BC88D5, ItemClassification.filler, category="Trinket"),
        "Modeling Clay"                      : ItemData(0x27BC88D6, ItemClassification.filler, category="Trinket"),
        "Kid's Drawing"                      : ItemData(0x27BC88D7, ItemClassification.filler, category="Trinket"),
        "Crystal Key"                        : ItemData(0x27BC88D8, ItemClassification.filler, category="Trinket"),
        "The Twins"                          : ItemData(0x27BC88D9, ItemClassification.filler, category="Trinket"),
        "Adoption Papers"                    : ItemData(0x27BC88DA, ItemClassification.filler, category="Trinket"),
        "Keeper's Bargain"                   : ItemData(0x27BC88DB, ItemClassification.filler, category="Trinket"),
        "Cursed Penny"                       : ItemData(0x27BC88DC, ItemClassification.filler, category="Trinket"),
        "Cricket Leg"                        : ItemData(0x27BC88DD, ItemClassification.filler, category="Trinket"),
        "Apollyon's Best Friend"             : ItemData(0x27BC88DE, ItemClassification.filler, category="Trinket"),
        "Polished Bone"                      : ItemData(0x27BC88DF, ItemClassification.filler, category="Trinket"),
        "Hollow Heart"                       : ItemData(0x27BC88E0, ItemClassification.filler, category="Trinket"),
        "Expansion Pack"                     : ItemData(0x27BC88E1, ItemClassification.filler, category="Item"),
        "Beth's Essence"                     : ItemData(0x27BC88E2, ItemClassification.filler, category="Trinket"),
        "RC Remote"                          : ItemData(0x27BC88E3, ItemClassification.filler, category="Trinket"),
        "Found Soul"                         : ItemData(0x27BC88E4, ItemClassification.filler, category="Trinket"),
        "Member Card"                        : ItemData(0x27BC88E5, ItemClassification.filler, category="Item"),
        "Golden Razor"                       : ItemData(0x27BC88E6, ItemClassification.filler, category="Item"),
        "Spindown Dice"                      : ItemData(0x27BC88E7, ItemClassification.filler, category="Item"),
        "Hypercoagulation"                   : ItemData(0x27BC88E8, ItemClassification.filler, category="Item"),
        "Bag of Crafting"                    : ItemData(0x27BC88E9, ItemClassification.filler, category="Item"),
        "Dark Arts"                          : ItemData(0x27BC88EA, ItemClassification.filler, category="Item"),
        "IBS"                                : ItemData(0x27BC88EB, ItemClassification.filler, category="Item"),
        "Sumptorium"                         : ItemData(0x27BC88EC, ItemClassification.filler, category="Item"),
        "Berserk!"                           : ItemData(0x27BC88ED, ItemClassification.filler, category="Item"),
        "Hemoptysis"                         : ItemData(0x27BC88EE, ItemClassification.filler, category="Item"),
        "Flip"                               : ItemData(0x27BC88EF, ItemClassification.filler, category="Item"),
        "Corrupted Data"                     : ItemData(0x27BC88F0, ItemClassification.useful),
        "Ghost Bombs"                        : ItemData(0x27BC88F1, ItemClassification.filler, category="Item"),
        "Gello"                              : ItemData(0x27BC88F2, ItemClassification.filler, category="Item"),
        "Keeper's Kin"                       : ItemData(0x27BC88F3, ItemClassification.filler, category="Item"),
        "Abyss"                              : ItemData(0x27BC88F4, ItemClassification.filler, category="Item"),
        "Decap Attack"                       : ItemData(0x27BC88F5, ItemClassification.filler, category="Item"),
        "Lemegeton"                          : ItemData(0x27BC88F6, ItemClassification.filler, category="Item"),
        "Anima Sola"                         : ItemData(0x27BC88F7, ItemClassification.filler, category="Item"),
        "Mega Chest"                         : ItemData(0x27BC88F8, ItemClassification.useful),
        "Queen of Hearts"                    : ItemData(0x27BC88F9, ItemClassification.useful),
        "Gold Pill"                          : ItemData(0x27BC88FA, ItemClassification.useful),
        "Black Sack"                         : ItemData(0x27BC88FB, ItemClassification.useful),
        "Charming Poop"                      : ItemData(0x27BC88FC, ItemClassification.useful),
        "Horse Pill"                         : ItemData(0x27BC88FD, ItemClassification.useful),
        "Crane Game"                         : ItemData(0x27BC88FE, ItemClassification.useful),
        "Hell Game"                          : ItemData(0x27BC88FF, ItemClassification.useful),
        "Wooden Chest"                       : ItemData(0x27BC8900, ItemClassification.useful),
        "Wild Card"                          : ItemData(0x27BC8901, ItemClassification.useful),
        "Haunted Chest"                      : ItemData(0x27BC8902, ItemClassification.useful),
        "Fool's Gold"                        : ItemData(0x27BC8903, ItemClassification.useful),
        "Golden Penny"                       : ItemData(0x27BC8904, ItemClassification.useful),
        "Rotten Beggar"                      : ItemData(0x27BC8905, ItemClassification.useful),
        "Golden Battery"                     : ItemData(0x27BC8906, ItemClassification.useful),
        "Confessional"                       : ItemData(0x27BC8907, ItemClassification.useful),
        "Golden Trinket"                     : ItemData(0x27BC8908, ItemClassification.useful),
        "Soul of Isaac"                      : ItemData(0x27BC8909, ItemClassification.useful),
        "Soul of Magdalene"                  : ItemData(0x27BC890A, ItemClassification.useful),
        "Soul of Cain"                       : ItemData(0x27BC890B, ItemClassification.useful),
        "Soul of Judas"                      : ItemData(0x27BC890C, ItemClassification.useful),
        "Soul of ???"                        : ItemData(0x27BC890D, ItemClassification.useful),
        "Soul of Eve"                        : ItemData(0x27BC890E, ItemClassification.useful),
        "Soul of Samson"                     : ItemData(0x27BC890F, ItemClassification.useful),
        "Soul of Azazel"                     : ItemData(0x27BC8910, ItemClassification.useful),
        "Soul of Lazarus"                    : ItemData(0x27BC8911, ItemClassification.useful),
        "Soul of Eden"                       : ItemData(0x27BC8912, ItemClassification.useful),
        "Soul of the Lost"                   : ItemData(0x27BC8913, ItemClassification.useful),
        "Soul of Lilith"                     : ItemData(0x27BC8914, ItemClassification.useful),
        "Soul of the Keeper"                 : ItemData(0x27BC8915, ItemClassification.useful),
        "Soul of Apollyon"                   : ItemData(0x27BC8916, ItemClassification.useful),
        "Soul of the Forgotten"              : ItemData(0x27BC8917, ItemClassification.useful),
        "Soul of Bethany"                    : ItemData(0x27BC8918, ItemClassification.useful),
        "Soul of Jacob"                      : ItemData(0x27BC8919, ItemClassification.useful),
        "A Strange Door"                     : ItemData(0x27BC891A, ItemClassification.progression, category="Stage"),
        "Death Certificate"                  : ItemData(0x27BC891B, ItemClassification.filler, category="Item"),
    #    "Dead God"                          : ItemData(0x27BC891C, ItemClassification.useful),
    #    "Play Online"                       : ItemData(0x27BC891D, ItemClassification.useful),
    #    "Win Online"                        : ItemData(0x27BC891E, ItemClassification.useful),
    #    "Win Online Daily"                  : ItemData(0x27BC891F, ItemClassification.useful),

        # Traps
        "Fool Trap"                          : ItemData(0x01, ItemClassification.trap),
        "High Priestess Trap"                : ItemData(0x02, ItemClassification.trap),
        "Tower Trap"                         : ItemData(0x03, ItemClassification.trap),
        "Emperor Trap"                       : ItemData(0x04, ItemClassification.trap),
        "Damocles Trap"                      : ItemData(0x05, ItemClassification.trap),
        "Chariot? Trap"                      : ItemData(0x06, ItemClassification.trap),
        "Stars? Trap"                        : ItemData(0x07, ItemClassification.trap),
        "Forget Me Now Trap"                 : ItemData(0x08, ItemClassification.trap),
        "TM Trainer Trap"                    : ItemData(0x09, ItemClassification.trap),
        "Clicker Trap"                       : ItemData(0x0A, ItemClassification.trap),
        "Run"                                : ItemData(0x0B, ItemClassification.trap),
        "Wheel of Fortune? Trap"             : ItemData(0x0C, ItemClassification.trap),
        "Cursed! Trap"                       : ItemData(0x0D, ItemClassification.trap),

        # Filler
        "Active Recharge"                    : ItemData(0x101, ItemClassification.filler),
        "Temporary Shield"                   : ItemData(0x102, ItemClassification.filler),
        "Three Coins"                        : ItemData(0x103, ItemClassification.filler),
        "Three Cards"                        : ItemData(0x104, ItemClassification.filler),
        "Three Runes"                        : ItemData(0x105, ItemClassification.filler),
        "Three Pills"                        : ItemData(0x106, ItemClassification.filler),
        "Three Hearts"                       : ItemData(0x107, ItemClassification.filler),
        "Three Bombs"                        : ItemData(0x108, ItemClassification.filler),
        "Three Keys"                         : ItemData(0x109, ItemClassification.filler),

        # Events
        "Victory"                            : ItemData(0x201, ItemClassification.progression_skip_balancing, "Event"),
    }

trap_items = (
    "Fool Trap",
    "High Priestess Trap",
    "Tower Trap",
    "Emperor Trap",
    "Damocles Trap",
    "Chariot? Trap",
    "Stars? Trap",
    "Forget Me Now Trap",
    "TM Trainer Trap",
    "Clicker Trap",
    "Run",
    "Wheel of Fortune? Trap",
    "Cursed! Trap"
)

filler_items = (
    "Active Recharge",
    "Temporary Shield",
    "Three Coins",
    "Three Cards",
    "Three Runes",
    "Three Pills",
    "Three Hearts",
    "Three Bombs",
    "Three Keys"
)