from math import floor
from typing import NamedTuple, Optional, TYPE_CHECKING

from BaseClasses import Location, Region, LocationProgressType
from worlds.generic.Rules import CollectionRule
from .Rules import can_reach_bluebaby_and_lamb, has_all_normal_characters, can_reach_all_marks, has_all_characters, has, \
    has_all

if TYPE_CHECKING:
    from . import TBOIWorld

class LocationData(NamedTuple):
    name: str
    code: Optional[int]
    region: str
    access_rule: CollectionRule = lambda state: True
    category: Optional[str] = None
    progress_type: Optional[LocationProgressType] = LocationProgressType.DEFAULT


class TBOILocation(Location):
    game = "The Binding of Isaac: Repentance+"

    def __init__(self, player: int, data: LocationData, region: Region):
        super().__init__(player, data.name, data.code, region)
        self.access_rule = data.access_rule
        self.progress_type = data.progress_type

def make_locations(world: Optional["TBOIWorld"]) -> list[LocationData]:
    if world is not None:
        ply = world.player
        baby_ratio = world.options.baby_ratio_required
    else:
        baby_ratio = 100

    locations: list[LocationData] = [
        ################################################################################################################
        #   CHARACTER MARKS
        ################################################################################################################
        LocationData("Isaac (Boss Rush)", 0x27BC86AA, "Chapter 3",
                     lambda state: has("Isaac", state, world, ply)),
        LocationData("Isaac (Mom's Heart)", 0x27BC86AB, "Chapter 4",
                     lambda state: has("Isaac", state, world, ply)),
        LocationData("Isaac (Satan)", 0x27BC86AC, "Sheol",
                     lambda state: has("Isaac", state, world, ply)),
        LocationData("Isaac (Isaac)", 0x27BC86AD, "Cathedral",
                     lambda state: has("Isaac", state, world, ply)),
        LocationData("Isaac (???)", 0x27BC86AE, "The Chest",
                     lambda state: has("Isaac", state, world, ply)),
        LocationData("Isaac (The Lamb)", 0x27BC86AF, "Dark Room",
                     lambda state: has("Isaac", state, world, ply)),
        LocationData("Isaac (Mega Satan)", 0x27BC86B0, "Mega Satan",
                     lambda state: has("Isaac", state, world , ply)),
        LocationData("Isaac (Hush)", 0x27BC86B1, "Blue Womb",
                     lambda state: has("Isaac", state, world, ply)),
        LocationData("Isaac (Delirium)", 0x27BC86B2, "The Void",
                     lambda state: has("Isaac", state, world, ply)),
        LocationData("Isaac (Mother)", 0x27BC86B3, "Corpse",
                     lambda state: has("Isaac", state, world, ply)),
        LocationData("Isaac (The Beast)", 0x27BC86B4, "Ascent",
                     lambda state: has("Isaac", state, world, ply)),
        LocationData("Isaac (Ultra Greed)", 0x27BC86B5, "Greed Mode",
                     lambda state: has("Isaac", state, world, ply)),
        LocationData("Isaac (Ultra Greedier)", 0x27BC86B6, "Greedier Mode",
                     lambda state: has("Isaac", state, world, ply)),
        LocationData("Tainted Isaac (??? & Lamb)", 0x27BC86B7, "Dark Room",
                     lambda state: has("The Broken", state, world, ply) and can_reach_bluebaby_and_lamb(ply, state)),
        LocationData("Tainted Isaac (Mega Satan)", 0x27BC86B8, "Mega Satan",
                     lambda state: has("The Broken", state, world, ply)),
        LocationData("Tainted Isaac (Hush & Boss Rush)", 0x27BC86B9, "Blue Womb",
                     lambda state: has("The Broken", state, world, ply)),
        LocationData("Tainted Isaac (Delirium)", 0x27BC86BA, "The Void",
                     lambda state: has("The Broken", state, world, ply)),
        LocationData("Tainted Isaac (Mother)", 0x27BC86BB, "Corpse",
                     lambda state: has("The Broken", state, world, ply)),
        LocationData("Tainted Isaac (The Beast)", 0x27BC86BC, "Ascent",
                     lambda state: has("The Broken", state, world, ply)),
        LocationData("Tainted Isaac (Ultra Greed)", 0x27BC86BD, "Greed Mode",
                     lambda state: has("The Broken", state, world, ply)),
        LocationData("Tainted Isaac (Ultra Greedier)", 0x27BC86BE, "Greedier Mode",
                     lambda state: has("The Broken", state, world, ply)),
        LocationData("Magdalene (Boss Rush)", 0x27BC86BF, "Chapter 3",
                     lambda state: has("Magdalene", state, world, ply)),
        LocationData("Magdalene (Mom's Heart)", 0x27BC86C0, "Chapter 4",
                     lambda state: has("Magdalene", state, world, ply)),
        LocationData("Magdalene (Satan)", 0x27BC86C1, "Sheol",
                     lambda state: has("Magdalene", state, world, ply)),
        LocationData("Magdalene (Isaac)", 0x27BC86C2, "Cathedral",
                     lambda state: has("Magdalene", state, world, ply)),
        LocationData("Magdalene (???)", 0x27BC86C3, "The Chest",
                     lambda state: has("Magdalene", state, world, ply)),
        LocationData("Magdalene (The Lamb)", 0x27BC86C4, "Dark Room",
                     lambda state: has("Magdalene", state, world, ply)),
        LocationData("Magdalene (Mega Satan)", 0x27BC86C5, "Mega Satan",
                     lambda state: has("Magdalene", state, world, ply)),
        LocationData("Magdalene (Hush)", 0x27BC86C6, "Blue Womb",
                     lambda state: has("Magdalene", state, world, ply)),
        LocationData("Magdalene (Delirium)", 0x27BC86C7, "The Void",
                     lambda state: has("Magdalene", state, world, ply)),
        LocationData("Magdalene (Mother)", 0x27BC86C8, "Corpse",
                     lambda state: has("Magdalene", state, world, ply)),
        LocationData("Magdalene (The Beast)", 0x27BC86C9, "Ascent",
                     lambda state: has("Magdalene", state, world, ply)),
        LocationData("Magdalene (Ultra Greed)", 0x27BC86CA, "Greed Mode",
                     lambda state: has("Magdalene", state, world, ply)),
        LocationData("Magdalene (Ultra Greedier)", 0x27BC86CB, "Greedier Mode",
                     lambda state: has("Magdalene", state, world, ply)),
        LocationData("Tainted Magdalene (??? & Lamb)", 0x27BC86CC, "Dark Room",
                     lambda state: has("The Dauntless", state, world, ply) and can_reach_bluebaby_and_lamb(ply, state)),
        LocationData("Tainted Magdalene (Mega Satan)", 0x27BC86CD, "Mega Satan",
                     lambda state: has("The Dauntless", state, world, ply)),
        LocationData("Tainted Magdalene (Hush & Boss Rush)", 0x27BC86CE, "Blue Womb",
                     lambda state: has("The Dauntless", state, world, ply)),
        LocationData("Tainted Magdalene (Delirium)", 0x27BC86CF, "The Void",
                     lambda state: has("The Dauntless", state, world, ply)),
        LocationData("Tainted Magdalene (Mother)", 0x27BC86D0, "Corpse",
                     lambda state: has("The Dauntless", state, world, ply)),
        LocationData("Tainted Magdalene (The Beast)", 0x27BC86D1, "Ascent",
                     lambda state: has("The Dauntless", state, world, ply)),
        LocationData("Tainted Magdalene (Ultra Greed)", 0x27BC86D2, "Greed Mode",
                     lambda state: has("The Dauntless", state, world, ply)),
        LocationData("Tainted Magdalene (Ultra Greedier)", 0x27BC86D3, "Greedier Mode",
                     lambda state: has("The Dauntless", state, world, ply)),
        LocationData("Judas (Boss Rush)", 0x27BC86D4, "Chapter 3",
                     lambda state: has("Judas", state, world, ply)),
        LocationData("Judas (Mom's Heart)", 0x27BC86D5, "Chapter 4",
                     lambda state: has("Judas", state, world, ply)),
        LocationData("Judas (Satan)", 0x27BC86D6, "Sheol",
                     lambda state: has("Judas", state, world, ply)),
        LocationData("Judas (Isaac)", 0x27BC86D7, "Cathedral",
                     lambda state: has("Judas", state, world, ply)),
        LocationData("Judas (???)", 0x27BC86D8, "The Chest",
                     lambda state: has("Judas", state, world, ply)),
        LocationData("Judas (The Lamb)", 0x27BC86D9, "Dark Room",
                     lambda state: has("Judas", state, world, ply)),
        LocationData("Judas (Mega Satan)", 0x27BC86DA, "Mega Satan",
                     lambda state: has("Judas", state, world, ply)),
        LocationData("Judas (Hush)", 0x27BC86DB, "Blue Womb",
                     lambda state: has("Judas", state, world, ply)),
        LocationData("Judas (Delirium)", 0x27BC86DC, "The Void",
                     lambda state: has("Judas", state, world, ply)),
        LocationData("Judas (Mother)", 0x27BC86DD, "Corpse",
                     lambda state: has("Judas", state, world, ply)),
        LocationData("Judas (The Beast)", 0x27BC86DE, "Ascent",
                     lambda state: has("Judas", state, world, ply)),
        LocationData("Judas (Ultra Greed)", 0x27BC86DF, "Greed Mode",
                     lambda state: has("Judas", state, world, ply)),
        LocationData("Judas (Ultra Greedier)", 0x27BC86E0, "Greedier Mode",
                     lambda state: has("Judas", state, world, ply)),
        LocationData("Tainted Judas (??? & Lamb)", 0x27BC86E1, "Dark Room",
                     lambda state: has("The Deceiver", state, world, ply) and can_reach_bluebaby_and_lamb(ply, state)),
        LocationData("Tainted Judas (Mega Satan)", 0x27BC86E2, "Mega Satan",
                     lambda state: has("The Deceiver", state, world, ply)),
        LocationData("Tainted Judas (Hush & Boss Rush)", 0x27BC86E3, "Blue Womb",
                     lambda state: has("The Deceiver", state, world, ply)),
        LocationData("Tainted Judas (Delirium)", 0x27BC86E4, "The Void",
                     lambda state: has("The Deceiver", state, world, ply)),
        LocationData("Tainted Judas (Mother)", 0x27BC86E5, "Corpse",
                     lambda state: has("The Deceiver", state, world, ply)),
        LocationData("Tainted Judas (The Beast)", 0x27BC86E6, "Ascent",
                     lambda state: has("The Deceiver", state, world, ply)),
        LocationData("Tainted Judas (Ultra Greed)", 0x27BC86E7, "Greed Mode",
                     lambda state: has("The Deceiver", state, world, ply)),
        LocationData("Tainted Judas (Ultra Greedier)", 0x27BC86E8, "Greedier Mode",
                     lambda state: has("The Deceiver", state, world, ply)),
        LocationData("Cain (Boss Rush)", 0x27BC86E9, "Chapter 3",
                     lambda state: has("Cain", state, world, ply)),
        LocationData("Cain (Mom's Heart)", 0x27BC86EA, "Chapter 4",
                     lambda state: has("Cain", state, world, ply)),
        LocationData("Cain (Satan)", 0x27BC86EB, "Sheol",
                     lambda state: has("Cain", state, world, ply)),
        LocationData("Cain (Isaac)", 0x27BC86EC, "Cathedral",
                     lambda state: has("Cain", state, world, ply)),
        LocationData("Cain (???)", 0x27BC86ED, "The Chest",
                     lambda state: has("Cain", state, world, ply)),
        LocationData("Cain (The Lamb)", 0x27BC86EE, "Dark Room",
                     lambda state: has("Cain", state, world, ply)),
        LocationData("Cain (Mega Satan)", 0x27BC86EF, "Mega Satan",
                     lambda state: has("Cain", state, world, ply)),
        LocationData("Cain (Hush)", 0x27BC86F0, "Blue Womb",
                     lambda state: has("Cain", state, world, ply)),
        LocationData("Cain (Delirium)", 0x27BC86F1, "The Void",
                     lambda state: has("Cain", state, world, ply)),
        LocationData("Cain (Mother)", 0x27BC86F2, "Corpse",
                     lambda state: has("Cain", state, world, ply)),
        LocationData("Cain (The Beast)", 0x27BC86F3, "Ascent",
                     lambda state: has("Cain", state, world, ply)),
        LocationData("Cain (Ultra Greed)", 0x27BC86F4, "Greed Mode",
                     lambda state: has("Cain", state, world, ply)),
        LocationData("Cain (Ultra Greedier)", 0x27BC86F5, "Greedier Mode",
                     lambda state: has("Cain", state, world, ply)),
        LocationData("Tainted Cain (??? & Lamb)", 0x27BC86F6, "Dark Room",
                     lambda state: has("The Hoarder", state, world, ply) and can_reach_bluebaby_and_lamb(ply, state)),
        LocationData("Tainted Cain (Mega Satan)", 0x27BC86F7, "Mega Satan",
                     lambda state: has("The Hoarder", state, world, ply)),
        LocationData("Tainted Cain (Hush & Boss Rush)", 0x27BC86F8, "Blue Womb",
                     lambda state: has("The Hoarder", state, world, ply)),
        LocationData("Tainted Cain (Delirium)", 0x27BC86F9, "The Void",
                     lambda state: has("The Hoarder", state, world, ply)),
        LocationData("Tainted Cain (Mother)", 0x27BC86FA, "Corpse",
                     lambda state: has("The Hoarder", state, world, ply)),
        LocationData("Tainted Cain (The Beast)", 0x27BC86FB, "Ascent",
                     lambda state: has("The Hoarder", state, world, ply)),
        LocationData("Tainted Cain (Ultra Greed)", 0x27BC86FC, "Greed Mode",
                     lambda state: has("The Hoarder", state, world, ply)),
        LocationData("Tainted Cain (Ultra Greedier)", 0x27BC86FD, "Greedier Mode",
                     lambda state: has("The Hoarder", state, world, ply)),
        LocationData("??? (Boss Rush)", 0x27BC86FE, "Chapter 3",
                     lambda state: has("???", state, world, ply)),
        LocationData("??? (Mom's Heart)", 0x27BC86FF, "Chapter 4",
                     lambda state: has("???", state, world, ply)),
        LocationData("??? (Satan)", 0x27BC8700, "Sheol",
                     lambda state: has("???", state, world, ply)),
        LocationData("??? (Isaac)", 0x27BC8701, "Cathedral",
                     lambda state: has("???", state, world, ply)),
        LocationData("??? (???)", 0x27BC8702, "The Chest",
                     lambda state: has("???", state, world, ply)),
        LocationData("??? (The Lamb)", 0x27BC8703, "Dark Room",
                     lambda state: has("???", state, world, ply)),
        LocationData("??? (Mega Satan)", 0x27BC8704, "Mega Satan",
                     lambda state: has("???", state, world, ply)),
        LocationData("??? (Hush)", 0x27BC8705, "Blue Womb",
                     lambda state: has("???", state, world, ply)),
        LocationData("??? (Delirium)", 0x27BC8706, "The Void",
                     lambda state: has("???", state, world, ply)),
        LocationData("??? (Mother)", 0x27BC8707, "Corpse",
                     lambda state: has("???", state, world, ply)),
        LocationData("??? (The Beast)", 0x27BC8708, "Ascent",
                     lambda state: has("???", state, world, ply)),
        LocationData("??? (Ultra Greed)", 0x27BC8709, "Greed Mode",
                     lambda state: has("???", state, world, ply)),
        LocationData("??? (Ultra Greedier)", 0x27BC870A, "Greedier Mode",
                     lambda state: has("???", state, world, ply)),
        LocationData("Tainted ??? (??? & Lamb)", 0x27BC870B, "Dark Room",
                     lambda state: has("The Soiled", state, world, ply) and can_reach_bluebaby_and_lamb(ply, state)),
        LocationData("Tainted ??? (Mega Satan)", 0x27BC870C, "Mega Satan",
                     lambda state: has("The Soiled", state, world, ply)),
        LocationData("Tainted ??? (Hush & Boss Rush)", 0x27BC870D, "Blue Womb",
                     lambda state: has("The Soiled", state, world, ply)),
        LocationData("Tainted ??? (Delirium)", 0x27BC870E, "The Void",
                     lambda state: has("The Soiled", state, world, ply)),
        LocationData("Tainted ??? (Mother)", 0x27BC870F, "Corpse",
                     lambda state: has("The Soiled", state, world, ply)),
        LocationData("Tainted ??? (The Beast)", 0x27BC8710, "Ascent",
                     lambda state: has("The Soiled", state, world, ply)),
        LocationData("Tainted ??? (Ultra Greed)", 0x27BC8711, "Greed Mode",
                     lambda state: has("The Soiled", state, world, ply)),
        LocationData("Tainted ??? (Ultra Greedier)", 0x27BC8712, "Greedier Mode",
                     lambda state: has("The Soiled", state, world, ply)),
        LocationData("Samson (Boss Rush)", 0x27BC8713, "Chapter 3",
                     lambda state: has("Samson", state, world, ply)),
        LocationData("Samson (Mom's Heart)", 0x27BC8714, "Chapter 4",
                     lambda state: has("Samson", state, world, ply)),
        LocationData("Samson (Satan)", 0x27BC8715, "Sheol",
                     lambda state: has("Samson", state, world, ply)),
        LocationData("Samson (Isaac)", 0x27BC8716, "Cathedral",
                     lambda state: has("Samson", state, world, ply)),
        LocationData("Samson (???)", 0x27BC8717, "The Chest",
                     lambda state: has("Samson", state, world, ply)),
        LocationData("Samson (The Lamb)", 0x27BC8718, "Dark Room",
                     lambda state: has("Samson", state, world, ply)),
        LocationData("Samson (Mega Satan)", 0x27BC8719, "Mega Satan",
                     lambda state: has("Samson", state, world, ply)),
        LocationData("Samson (Hush)", 0x27BC871A, "Blue Womb",
                     lambda state: has("Samson", state, world, ply)),
        LocationData("Samson (Delirium)", 0x27BC871B, "The Void",
                     lambda state: has("Samson", state, world, ply)),
        LocationData("Samson (Mother)", 0x27BC871C, "Corpse",
                     lambda state: has("Samson", state, world, ply)),
        LocationData("Samson (The Beast)", 0x27BC871D, "Ascent",
                     lambda state: has("Samson", state, world, ply)),
        LocationData("Samson (Ultra Greed)", 0x27BC871E, "Greed Mode",
                     lambda state: has("Samson", state, world, ply)),
        LocationData("Samson (Ultra Greedier)", 0x27BC871F, "Greedier Mode",
                     lambda state: has("Samson", state, world, ply)),
        LocationData("Tainted Samson (??? & Lamb)", 0x27BC8720, "Dark Room",
                     lambda state: has("The Savage", state, world, ply) and can_reach_bluebaby_and_lamb(ply, state)),
        LocationData("Tainted Samson (Mega Satan)", 0x27BC8721, "Mega Satan",
                     lambda state: has("The Savage", state, world, ply)),
        LocationData("Tainted Samson (Hush & Boss Rush)", 0x27BC8722, "Blue Womb",
                     lambda state: has("The Savage", state, world, ply)),
        LocationData("Tainted Samson (Delirium)", 0x27BC8723, "The Void",
                     lambda state: has("The Savage", state, world, ply)),
        LocationData("Tainted Samson (Mother)", 0x27BC8724, "Corpse",
                     lambda state: has("The Savage", state, world, ply)),
        LocationData("Tainted Samson (The Beast)", 0x27BC8725, "Ascent",
                     lambda state: has("The Savage", state, world, ply)),
        LocationData("Tainted Samson (Ultra Greed)", 0x27BC8726, "Greed Mode",
                     lambda state: has("The Savage", state, world, ply)),
        LocationData("Tainted Samson (Ultra Greedier)", 0x27BC8727, "Greedier Mode",
                     lambda state: has("The Savage", state, world, ply)),
        LocationData("Eve (Boss Rush)", 0x27BC8728, "Chapter 3",
                     lambda state: has("Eve", state, world, ply)),
        LocationData("Eve (Mom's Heart)", 0x27BC8729, "Chapter 4",
                     lambda state: has("Eve", state, world, ply)),
        LocationData("Eve (Satan)", 0x27BC872A, "Sheol",
                     lambda state: has("Eve", state, world, ply)),
        LocationData("Eve (Isaac)", 0x27BC872B, "Cathedral",
                     lambda state: has("Eve", state, world, ply)),
        LocationData("Eve (???)", 0x27BC872C, "The Chest",
                     lambda state: has("Eve", state, world, ply)),
        LocationData("Eve (The Lamb)", 0x27BC872D, "Dark Room",
                     lambda state: has("Eve", state, world, ply)),
        LocationData("Eve (Mega Satan)", 0x27BC872E, "Mega Satan",
                     lambda state: has("Eve", state, world, ply)),
        LocationData("Eve (Hush)", 0x27BC872F, "Blue Womb",
                     lambda state: has("Eve", state, world, ply)),
        LocationData("Eve (Delirium)", 0x27BC8730, "The Void",
                     lambda state: has("Eve", state, world, ply)),
        LocationData("Eve (Mother)", 0x27BC8731, "Corpse",
                     lambda state: has("Eve", state, world, ply)),
        LocationData("Eve (The Beast)", 0x27BC8732, "Ascent",
                     lambda state: has("Eve", state, world, ply)),
        LocationData("Eve (Ultra Greed)", 0x27BC8733, "Greed Mode",
                     lambda state: has("Eve", state, world, ply)),
        LocationData("Eve (Ultra Greedier)", 0x27BC8734, "Greedier Mode",
                     lambda state: has("Eve", state, world, ply)),
        LocationData("Tainted Eve (??? & Lamb)", 0x27BC8735, "Dark Room",
                     lambda state: has("The Curdled", state, world, ply) and can_reach_bluebaby_and_lamb(ply, state)),
        LocationData("Tainted Eve (Mega Satan)", 0x27BC8736, "Mega Satan",
                     lambda state: has("The Curdled", state, world, ply)),
        LocationData("Tainted Eve (Hush & Boss Rush)", 0x27BC8737, "Blue Womb",
                     lambda state: has("The Curdled", state, world, ply)),
        LocationData("Tainted Eve (Delirium)", 0x27BC8738, "The Void",
                     lambda state: has("The Curdled", state, world, ply)),
        LocationData("Tainted Eve (Mother)", 0x27BC8739, "Corpse",
                     lambda state: has("The Curdled", state, world, ply)),
        LocationData("Tainted Eve (The Beast)", 0x27BC873A, "Ascent",
                     lambda state: has("The Curdled", state, world, ply)),
        LocationData("Tainted Eve (Ultra Greed)", 0x27BC873B, "Greed Mode",
                     lambda state: has("The Curdled", state, world, ply)),
        LocationData("Tainted Eve (Ultra Greedier)", 0x27BC873C, "Greedier Mode",
                     lambda state: has("The Curdled", state, world, ply)),
        LocationData("Azazel (Boss Rush)", 0x27BC873D, "Chapter 3",
                     lambda state: has("Azazel", state, world, ply)),
        LocationData("Azazel (Mom's Heart)", 0x27BC873E, "Chapter 4",
                     lambda state: has("Azazel", state, world, ply)),
        LocationData("Azazel (Satan)", 0x27BC873F, "Sheol",
                     lambda state: has("Azazel", state, world, ply)),
        LocationData("Azazel (Isaac)", 0x27BC8740, "Cathedral",
                     lambda state: has("Azazel", state, world, ply)),
        LocationData("Azazel (???)", 0x27BC8741, "The Chest",
                     lambda state: has("Azazel", state, world, ply)),
        LocationData("Azazel (The Lamb)", 0x27BC8742, "Dark Room",
                     lambda state: has("Azazel", state, world, ply)),
        LocationData("Azazel (Mega Satan)", 0x27BC8743, "Mega Satan",
                     lambda state: has("Azazel", state, world, ply)),
        LocationData("Azazel (Hush)", 0x27BC8744, "Blue Womb",
                     lambda state: has("Azazel", state, world, ply)),
        LocationData("Azazel (Delirium)", 0x27BC8745, "The Void",
                     lambda state: has("Azazel", state, world, ply)),
        LocationData("Azazel (Mother)", 0x27BC8746, "Corpse",
                     lambda state: has("Azazel", state, world, ply)),
        LocationData("Azazel (The Beast)", 0x27BC8747, "Ascent",
                     lambda state: has("Azazel", state, world, ply)),
        LocationData("Azazel (Ultra Greed)", 0x27BC8748, "Greed Mode",
                     lambda state: has("Azazel", state, world, ply)),
        LocationData("Azazel (Ultra Greedier)", 0x27BC8749, "Greedier Mode",
                     lambda state: has("Azazel", state, world, ply)),
        LocationData("Tainted Azazel (??? & Lamb)", 0x27BC874A, "Dark Room",
                     lambda state: has("The Benighted", state, world, ply) and can_reach_bluebaby_and_lamb(ply, state)),
        LocationData("Tainted Azazel (Mega Satan)", 0x27BC874B, "Mega Satan",
                     lambda state: has("The Benighted", state, world, ply)),
        LocationData("Tainted Azazel (Hush & Boss Rush)", 0x27BC874C, "Blue Womb",
                     lambda state: has("The Benighted", state, world, ply)),
        LocationData("Tainted Azazel (Delirium)", 0x27BC874D, "The Void",
                     lambda state: has("The Benighted", state, world, ply)),
        LocationData("Tainted Azazel (Mother)", 0x27BC874E, "Corpse",
                     lambda state: has("The Benighted", state, world, ply)),
        LocationData("Tainted Azazel (The Beast)", 0x27BC874F, "Ascent",
                     lambda state: has("The Benighted", state, world, ply)),
        LocationData("Tainted Azazel (Ultra Greed)", 0x27BC8750, "Greed Mode",
                     lambda state: has("The Benighted", state, world, ply)),
        LocationData("Tainted Azazel (Ultra Greedier)", 0x27BC8751, "Greedier Mode",
                     lambda state: has("The Benighted", state, world, ply)),
        LocationData("Lazarus (Boss Rush)", 0x27BC8752, "Chapter 3",
                     lambda state: has("Lazarus", state, world, ply)),
        LocationData("Lazarus (Mom's Heart)", 0x27BC8753, "Chapter 4",
                     lambda state: has("Lazarus", state, world, ply)),
        LocationData("Lazarus (Satan)", 0x27BC8754, "Sheol",
                     lambda state: has("Lazarus", state, world, ply)),
        LocationData("Lazarus (Isaac)", 0x27BC8755, "Cathedral",
                     lambda state: has("Lazarus", state, world, ply)),
        LocationData("Lazarus (???)", 0x27BC8756, "The Chest",
                     lambda state: has("Lazarus", state, world, ply)),
        LocationData("Lazarus (The Lamb)", 0x27BC8757, "Dark Room",
                     lambda state: has("Lazarus", state, world, ply)),
        LocationData("Lazarus (Mega Satan)", 0x27BC8758, "Mega Satan",
                     lambda state: has("Lazarus", state, world, ply)),
        LocationData("Lazarus (Hush)", 0x27BC8759, "Blue Womb",
                     lambda state: has("Lazarus", state, world, ply)),
        LocationData("Lazarus (Delirium)", 0x27BC875A, "The Void",
                     lambda state: has("Lazarus", state, world, ply)),
        LocationData("Lazarus (Mother)", 0x27BC875B, "Corpse",
                     lambda state: has("Lazarus", state, world, ply)),
        LocationData("Lazarus (The Beast)", 0x27BC875C, "Ascent",
                     lambda state: has("Lazarus", state, world, ply)),
        LocationData("Lazarus (Ultra Greed)", 0x27BC875D, "Greed Mode",
                     lambda state: has("Lazarus", state, world, ply)),
        LocationData("Lazarus (Ultra Greedier)", 0x27BC875E, "Greedier Mode",
                     lambda state: has("Lazarus", state, world, ply)),
        LocationData("Tainted Lazarus (??? & Lamb)", 0x27BC875F, "Dark Room",
                     lambda state: has("The Enigma", state, world, ply) and can_reach_bluebaby_and_lamb(ply, state)),
        LocationData("Tainted Lazarus (Mega Satan)", 0x27BC8760, "Mega Satan",
                     lambda state: has("The Enigma", state, world, ply)),
        LocationData("Tainted Lazarus (Hush & Boss Rush)", 0x27BC8761, "Blue Womb",
                     lambda state: has("The Enigma", state, world, ply)),
        LocationData("Tainted Lazarus (Delirium)", 0x27BC8762, "The Void",
                     lambda state: has("The Enigma", state, world, ply)),
        LocationData("Tainted Lazarus (Mother)", 0x27BC8763, "Corpse",
                     lambda state: has("The Enigma", state, world, ply)),
        LocationData("Tainted Lazarus (The Beast)", 0x27BC8764, "Ascent",
                     lambda state: has("The Enigma", state, world, ply)),
        LocationData("Tainted Lazarus (Ultra Greed)", 0x27BC8765, "Greed Mode",
                     lambda state: has("The Enigma", state, world, ply)),
        LocationData("Tainted Lazarus (Ultra Greedier)", 0x27BC8766, "Greedier Mode",
                     lambda state: has("The Enigma", state, world, ply)),
        LocationData("Eden (Boss Rush)", 0x27BC8767, "Chapter 3",
                     lambda state: has("Eden", state, world, ply)),
        LocationData("Eden (Mom's Heart)", 0x27BC8768, "Chapter 4",
                     lambda state: has("Eden", state, world, ply)),
        LocationData("Eden (Satan)", 0x27BC8769, "Sheol",
                     lambda state: has("Eden", state, world, ply)),
        LocationData("Eden (Isaac)", 0x27BC876A, "Cathedral",
                     lambda state: has("Eden", state, world, ply)),
        LocationData("Eden (???)", 0x27BC876B, "The Chest",
                     lambda state: has("Eden", state, world, ply)),
        LocationData("Eden (The Lamb)", 0x27BC876C, "Dark Room",
                     lambda state: has("Eden", state, world, ply)),
        LocationData("Eden (Mega Satan)", 0x27BC876D, "Mega Satan",
                     lambda state: has("Eden", state, world, ply)),
        LocationData("Eden (Hush)", 0x27BC876E, "Blue Womb",
                     lambda state: has("Eden", state, world, ply)),
        LocationData("Eden (Delirium)", 0x27BC876F, "The Void",
                     lambda state: has("Eden", state, world, ply)),
        LocationData("Eden (Mother)", 0x27BC8770, "Corpse",
                     lambda state: has("Eden", state, world, ply)),
        LocationData("Eden (The Beast)", 0x27BC8771, "Ascent",
                     lambda state: has("Eden", state, world, ply)),
        LocationData("Eden (Ultra Greed)", 0x27BC8772, "Greed Mode",
                     lambda state: has("Eden", state, world, ply)),
        LocationData("Eden (Ultra Greedier)", 0x27BC8773, "Greedier Mode",
                     lambda state: has("Eden", state, world, ply)),
        LocationData("Tainted Eden (??? & Lamb)", 0x27BC8774, "Dark Room",
                     lambda state: has("The Capricious", state, world, ply) and can_reach_bluebaby_and_lamb(ply, state)),
        LocationData("Tainted Eden (Mega Satan)", 0x27BC8775, "Mega Satan",
                     lambda state: has("The Capricious", state, world, ply)),
        LocationData("Tainted Eden (Hush & Boss Rush)", 0x27BC8776, "Blue Womb",
                     lambda state: has("The Capricious", state, world, ply)),
        LocationData("Tainted Eden (Delirium)", 0x27BC8777, "The Void",
                     lambda state: has("The Capricious", state, world, ply)),
        LocationData("Tainted Eden (Mother)", 0x27BC8778, "Corpse",
                     lambda state: has("The Capricious", state, world, ply)),
        LocationData("Tainted Eden (The Beast)", 0x27BC8779, "Ascent",
                     lambda state: has("The Capricious", state, world, ply)),
        LocationData("Tainted Eden (Ultra Greed)", 0x27BC877A, "Greed Mode",
                     lambda state: has("The Capricious", state, world, ply)),
        LocationData("Tainted Eden (Ultra Greedier)", 0x27BC877B, "Greedier Mode",
                     lambda state: has("The Capricious", state, world, ply)),
        LocationData("Lost (Boss Rush)", 0x27BC877C, "Chapter 3",
                     lambda state: has("Lost", state, world, ply)),
        LocationData("Lost (Mom's Heart)", 0x27BC877D, "Chapter 4",
                     lambda state: has("Lost", state, world, ply)),
        LocationData("Lost (Satan)", 0x27BC877E, "Sheol",
                     lambda state: has("Lost", state, world, ply)),
        LocationData("Lost (Isaac)", 0x27BC877F, "Cathedral",
                     lambda state: has("Lost", state, world, ply)),
        LocationData("Lost (???)", 0x27BC8780, "The Chest",
                     lambda state: has("Lost", state, world, ply)),
        LocationData("Lost (The Lamb)", 0x27BC8781, "Dark Room",
                     lambda state: has("Lost", state, world, ply)),
        LocationData("Lost (Mega Satan)", 0x27BC8782, "Mega Satan",
                     lambda state: has("Lost", state, world, ply)),
        LocationData("Lost (Hush)", 0x27BC8783, "Blue Womb",
                     lambda state: has("Lost", state, world, ply)),
        LocationData("Lost (Delirium)", 0x27BC8784, "The Void",
                     lambda state: has("Lost", state, world, ply)),
        LocationData("Lost (Mother)", 0x27BC8785, "Corpse",
                     lambda state: has("Lost", state, world, ply)),
        LocationData("Lost (The Beast)", 0x27BC8786, "Ascent",
                     lambda state: has("Lost", state, world, ply)),
        LocationData("Lost (Ultra Greed)", 0x27BC8787, "Greed Mode",
                     lambda state: has("Lost", state, world, ply)),
        LocationData("Lost (Ultra Greedier)", 0x27BC8788, "Greedier Mode",
                     lambda state: has("Lost", state, world, ply)),
        LocationData("Tainted Lost (??? & Lamb)", 0x27BC8789, "Dark Room",
                     lambda state: has("The Baleful", state, world, ply) and can_reach_bluebaby_and_lamb(ply, state)),
        LocationData("Tainted Lost (Mega Satan)", 0x27BC878A, "Mega Satan",
                     lambda state: has("The Baleful", state, world, ply)),
        LocationData("Tainted Lost (Hush & Boss Rush)", 0x27BC878B, "Blue Womb",
                     lambda state: has("The Baleful", state, world, ply)),
        LocationData("Tainted Lost (Delirium)", 0x27BC878C, "The Void",
                     lambda state: has("The Baleful", state, world, ply)),
        LocationData("Tainted Lost (Mother)", 0x27BC878D, "Corpse",
                     lambda state: has("The Baleful", state, world, ply)),
        LocationData("Tainted Lost (The Beast)", 0x27BC878E, "Ascent",
                     lambda state: has("The Baleful", state, world, ply)),
        LocationData("Tainted Lost (Ultra Greed)", 0x27BC878F, "Greed Mode",
                     lambda state: has("The Baleful", state, world, ply)),
        LocationData("Tainted Lost (Ultra Greedier)", 0x27BC8790, "Greedier Mode",
                     lambda state: has("The Baleful", state, world, ply)),
        LocationData("Lilith (Boss Rush)", 0x27BC8791, "Chapter 3",
                     lambda state: has("Lilith", state, world, ply)),
        LocationData("Lilith (Mom's Heart)", 0x27BC8792, "Chapter 4",
                     lambda state: has("Lilith", state, world, ply)),
        LocationData("Lilith (Satan)", 0x27BC8793, "Sheol",
                     lambda state: has("Lilith", state, world, ply)),
        LocationData("Lilith (Isaac)", 0x27BC8794, "Cathedral",
                     lambda state: has("Lilith", state, world, ply)),
        LocationData("Lilith (???)", 0x27BC8795, "The Chest",
                     lambda state: has("Lilith", state, world, ply)),
        LocationData("Lilith (The Lamb)", 0x27BC8796, "Dark Room",
                     lambda state: has("Lilith", state, world, ply)),
        LocationData("Lilith (Mega Satan)", 0x27BC8797, "Mega Satan",
                     lambda state: has("Lilith", state, world, ply)),
        LocationData("Lilith (Hush)", 0x27BC8798, "Blue Womb",
                     lambda state: has("Lilith", state, world, ply)),
        LocationData("Lilith (Delirium)", 0x27BC8799, "The Void",
                     lambda state: has("Lilith", state, world, ply)),
        LocationData("Lilith (Mother)", 0x27BC879A, "Corpse",
                     lambda state: has("Lilith", state, world, ply)),
        LocationData("Lilith (The Beast)", 0x27BC879B, "Ascent",
                     lambda state: has("Lilith", state, world, ply)),
        LocationData("Lilith (Ultra Greed)", 0x27BC879C, "Greed Mode",
                     lambda state: has("Lilith", state, world, ply)),
        LocationData("Lilith (Ultra Greedier)", 0x27BC879D, "Greedier Mode",
                     lambda state: has("Lilith", state, world, ply)),
        LocationData("Tainted Lilith (??? & Lamb)", 0x27BC879E, "Dark Room",
                     lambda state: has("The Harlot", state, world, ply) and can_reach_bluebaby_and_lamb(ply, state)),
        LocationData("Tainted Lilith (Mega Satan)", 0x27BC879F, "Mega Satan",
                     lambda state: has("The Harlot", state, world, ply)),
        LocationData("Tainted Lilith (Hush & Boss Rush)", 0x27BC87A0, "Blue Womb",
                     lambda state: has("The Harlot", state, world, ply)),
        LocationData("Tainted Lilith (Delirium)", 0x27BC87A1, "The Void",
                     lambda state: has("The Harlot", state, world, ply)),
        LocationData("Tainted Lilith (Mother)", 0x27BC87A2, "Corpse",
                     lambda state: has("The Harlot", state, world, ply)),
        LocationData("Tainted Lilith (The Beast)", 0x27BC87A3, "Ascent",
                     lambda state: has("The Harlot", state, world, ply)),
        LocationData("Tainted Lilith (Ultra Greed)", 0x27BC87A4, "Greed Mode",
                     lambda state: has("The Harlot", state, world, ply)),
        LocationData("Tainted Lilith (Ultra Greedier)", 0x27BC87A5, "Greedier Mode",
                     lambda state: has("The Harlot", state, world, ply)),
        LocationData("Keeper (Boss Rush)", 0x27BC87A6, "Chapter 3",
                     lambda state: has("Keeper", state, world, ply)),
        LocationData("Keeper (Mom's Heart)", 0x27BC87A7, "Chapter 4",
                     lambda state: has("Keeper", state, world, ply)),
        LocationData("Keeper (Satan)", 0x27BC87A8, "Sheol",
                     lambda state: has("Keeper", state, world, ply)),
        LocationData("Keeper (Isaac)", 0x27BC87A9, "Cathedral",
                     lambda state: has("Keeper", state, world, ply)),
        LocationData("Keeper (???)", 0x27BC87AA, "The Chest",
                     lambda state: has("Keeper", state, world, ply)),
        LocationData("Keeper (The Lamb)", 0x27BC87AB, "Dark Room",
                     lambda state: has("Keeper", state, world, ply)),
        LocationData("Keeper (Mega Satan)", 0x27BC87AC, "Mega Satan",
                     lambda state: has("Keeper", state, world, ply)),
        LocationData("Keeper (Hush)", 0x27BC87AD, "Blue Womb",
                     lambda state: has("Keeper", state, world, ply)),
        LocationData("Keeper (Delirium)", 0x27BC87AE, "The Void",
                     lambda state: has("Keeper", state, world, ply)),
        LocationData("Keeper (Mother)", 0x27BC87AF, "Corpse",
                     lambda state: has("Keeper", state, world, ply)),
        LocationData("Keeper (The Beast)", 0x27BC87B0, "Ascent",
                     lambda state: has("Keeper", state, world, ply)),
        LocationData("Keeper (Ultra Greed)", 0x27BC87B1, "Greed Mode",
                     lambda state: has("Keeper", state, world, ply)),
        LocationData("Keeper (Ultra Greedier)", 0x27BC87B2, "Greedier Mode",
                     lambda state: has("Keeper", state, world, ply)),
        LocationData("Tainted Keeper (??? & Lamb)", 0x27BC87B3, "Dark Room",
                     lambda state: has("The Miser", state, world, ply) and can_reach_bluebaby_and_lamb(ply, state)),
        LocationData("Tainted Keeper (Mega Satan)", 0x27BC87B4, "Mega Satan",
                     lambda state: has("The Miser", state, world, ply)),
        LocationData("Tainted Keeper (Hush & Boss Rush)", 0x27BC87B5, "Blue Womb",
                     lambda state: has("The Miser", state, world, ply)),
        LocationData("Tainted Keeper (Delirium)", 0x27BC87B6, "The Void",
                     lambda state: has("The Miser", state, world, ply)),
        LocationData("Tainted Keeper (Mother)", 0x27BC87B7, "Corpse",
                     lambda state: has("The Miser", state, world, ply)),
        LocationData("Tainted Keeper (The Beast)", 0x27BC87B8, "Ascent",
                     lambda state: has("The Miser", state, world, ply)),
        LocationData("Tainted Keeper (Ultra Greed)", 0x27BC87B9, "Greed Mode",
                     lambda state: has("The Miser", state, world, ply)),
        LocationData("Tainted Keeper (Ultra Greedier)", 0x27BC87BA, "Greedier Mode",
                     lambda state: has("The Miser", state, world, ply)),
        LocationData("Apollyon (Boss Rush)", 0x27BC87BB, "Chapter 3",
                     lambda state: has("Apollyon", state, world, ply)),
        LocationData("Apollyon (Mom's Heart)", 0x27BC87BC, "Chapter 4",
                     lambda state: has("Apollyon", state, world, ply)),
        LocationData("Apollyon (Satan)", 0x27BC87BD, "Sheol",
                     lambda state: has("Apollyon", state, world, ply)),
        LocationData("Apollyon (Isaac)", 0x27BC87BE, "Cathedral",
                     lambda state: has("Apollyon", state, world, ply)),
        LocationData("Apollyon (???)", 0x27BC87BF, "The Chest",
                     lambda state: has("Apollyon", state, world, ply)),
        LocationData("Apollyon (The Lamb)", 0x27BC87C0, "Dark Room",
                     lambda state: has("Apollyon", state, world, ply)),
        LocationData("Apollyon (Mega Satan)", 0x27BC87C1, "Mega Satan",
                     lambda state: has("Apollyon", state, world, ply)),
        LocationData("Apollyon (Hush)", 0x27BC87C2, "Blue Womb",
                     lambda state: has("Apollyon", state, world, ply)),
        LocationData("Apollyon (Delirium)", 0x27BC87C3, "The Void",
                     lambda state: has("Apollyon", state, world, ply)),
        LocationData("Apollyon (Mother)", 0x27BC87C4, "Corpse",
                     lambda state: has("Apollyon", state, world, ply)),
        LocationData("Apollyon (The Beast)", 0x27BC87C5, "Ascent",
                     lambda state: has("Apollyon", state, world, ply)),
        LocationData("Apollyon (Ultra Greed)", 0x27BC87C6, "Greed Mode",
                     lambda state: has("Apollyon", state, world, ply)),
        LocationData("Apollyon (Ultra Greedier)", 0x27BC87C7, "Greedier Mode",
                     lambda state: has("Apollyon", state, world, ply)),
        LocationData("Tainted Apollyon (??? & Lamb)", 0x27BC87C8, "Dark Room",
                     lambda state: has("The Empty", state, world, ply) and can_reach_bluebaby_and_lamb(ply, state)),
        LocationData("Tainted Apollyon (Mega Satan)", 0x27BC87C9, "Mega Satan",
                     lambda state: has("The Empty", state, world, ply)),
        LocationData("Tainted Apollyon (Hush & Boss Rush)", 0x27BC87CA, "Blue Womb",
                     lambda state: has("The Empty", state, world, ply)),
        LocationData("Tainted Apollyon (Delirium)", 0x27BC87CB, "The Void",
                     lambda state: has("The Empty", state, world, ply)),
        LocationData("Tainted Apollyon (Mother)", 0x27BC87CC, "Corpse",
                     lambda state: has("The Empty", state, world, ply)),
        LocationData("Tainted Apollyon (The Beast)", 0x27BC87CD, "Ascent",
                     lambda state: has("The Empty", state, world, ply)),
        LocationData("Tainted Apollyon (Ultra Greed)", 0x27BC87CE, "Greed Mode",
                     lambda state: has("The Empty", state, world, ply)),
        LocationData("Tainted Apollyon (Ultra Greedier)", 0x27BC87CF, "Greedier Mode",
                     lambda state: has("The Empty", state, world, ply)),
        LocationData("Forgotten (Boss Rush)", 0x27BC87D0, "Chapter 3",
                     lambda state: has("Forgotten", state, world, ply)),
        LocationData("Forgotten (Mom's Heart)", 0x27BC87D1, "Chapter 4",
                     lambda state: has("Forgotten", state, world, ply)),
        LocationData("Forgotten (Satan)", 0x27BC87D2, "Sheol",
                     lambda state: has("Forgotten", state, world, ply)),
        LocationData("Forgotten (Isaac)", 0x27BC87D3, "Cathedral",
                     lambda state: has("Forgotten", state, world, ply)),
        LocationData("Forgotten (???)", 0x27BC87D4, "The Chest",
                     lambda state: has("Forgotten", state, world, ply)),
        LocationData("Forgotten (The Lamb)", 0x27BC87D5, "Dark Room",
                     lambda state: has("Forgotten", state, world, ply)),
        LocationData("Forgotten (Mega Satan)", 0x27BC87D6, "Mega Satan",
                     lambda state: has("Forgotten", state, world, ply)),
        LocationData("Forgotten (Hush)", 0x27BC87D7, "Blue Womb",
                     lambda state: has("Forgotten", state, world, ply)),
        LocationData("Forgotten (Delirium)", 0x27BC87D8, "The Void",
                     lambda state: has("Forgotten", state, world, ply)),
        LocationData("Forgotten (Mother)", 0x27BC87D9, "Corpse",
                     lambda state: has("Forgotten", state, world, ply)),
        LocationData("Forgotten (The Beast)", 0x27BC87DA, "Ascent",
                     lambda state: has("Forgotten", state, world, ply)),
        LocationData("Forgotten (Ultra Greed)", 0x27BC87DB, "Greed Mode",
                     lambda state: has("Forgotten", state, world, ply)),
        LocationData("Forgotten (Ultra Greedier)", 0x27BC87DC, "Greedier Mode",
                     lambda state: has("Forgotten", state, world, ply)),
        LocationData("Tainted Forgotten (??? & Lamb)", 0x27BC87DD, "Dark Room",
                     lambda state: has("The Fettered", state, world, ply) and can_reach_bluebaby_and_lamb(ply, state)),
        LocationData("Tainted Forgotten (Mega Satan)", 0x27BC87DE, "Mega Satan",
                     lambda state: has("The Fettered", state, world, ply)),
        LocationData("Tainted Forgotten (Hush & Boss Rush)", 0x27BC87DF, "Blue Womb",
                     lambda state: has("The Fettered", state, world, ply)),
        LocationData("Tainted Forgotten (Delirium)", 0x27BC87E0, "The Void",
                     lambda state: has("The Fettered", state, world, ply)),
        LocationData("Tainted Forgotten (Mother)", 0x27BC87E1, "Corpse",
                     lambda state: has("The Fettered", state, world, ply)),
        LocationData("Tainted Forgotten (The Beast)", 0x27BC87E2, "Ascent",
                     lambda state: has("The Fettered", state, world, ply)),
        LocationData("Tainted Forgotten (Ultra Greed)", 0x27BC87E3, "Greed Mode",
                     lambda state: has("The Fettered", state, world, ply)),
        LocationData("Tainted Forgotten (Ultra Greedier)", 0x27BC87E4, "Greedier Mode",
                     lambda state: has("The Fettered", state, world, ply)),
        LocationData("Bethany (Boss Rush)", 0x27BC87E5, "Chapter 3",
                     lambda state: has("Bethany", state, world, ply)),
        LocationData("Bethany (Mom's Heart)", 0x27BC87E6, "Chapter 4",
                     lambda state: has("Bethany", state, world, ply)),
        LocationData("Bethany (Satan)", 0x27BC87E7, "Sheol",
                     lambda state: has("Bethany", state, world, ply)),
        LocationData("Bethany (Isaac)", 0x27BC87E8, "Cathedral",
                     lambda state: has("Bethany", state, world, ply)),
        LocationData("Bethany (???)", 0x27BC87E9, "The Chest",
                     lambda state: has("Bethany", state, world, ply)),
        LocationData("Bethany (The Lamb)", 0x27BC87EA, "Dark Room",
                     lambda state: has("Bethany", state, world, ply)),
        LocationData("Bethany (Mega Satan)", 0x27BC87EB, "Mega Satan",
                     lambda state: has("Bethany", state, world, ply)),
        LocationData("Bethany (Hush)", 0x27BC87EC, "Blue Womb",
                     lambda state: has("Bethany", state, world, ply)),
        LocationData("Bethany (Delirium)", 0x27BC87ED, "The Void",
                     lambda state: has("Bethany", state, world, ply)),
        LocationData("Bethany (Mother)", 0x27BC87EE, "Corpse",
                     lambda state: has("Bethany", state, world, ply)),
        LocationData("Bethany (The Beast)", 0x27BC87EF, "Ascent",
                     lambda state: has("Bethany", state, world, ply)),
        LocationData("Bethany (Ultra Greed)", 0x27BC87F0, "Greed Mode",
                     lambda state: has("Bethany", state, world, ply)),
        LocationData("Bethany (Ultra Greedier)", 0x27BC87F1, "Greedier Mode",
                     lambda state: has("Bethany", state, world, ply)),
        LocationData("Tainted Bethany (??? & Lamb)", 0x27BC87F2, "Dark Room",
                     lambda state: has("The Zealot", state, world, ply) and can_reach_bluebaby_and_lamb(ply, state)),
        LocationData("Tainted Bethany (Mega Satan)", 0x27BC87F3, "Mega Satan",
                     lambda state: has("The Zealot", state, world, ply)),
        LocationData("Tainted Bethany (Hush & Boss Rush)", 0x27BC87F4, "Blue Womb",
                     lambda state: has("The Zealot", state, world, ply)),
        LocationData("Tainted Bethany (Delirium)", 0x27BC87F5, "The Void",
                     lambda state: has("The Zealot", state, world, ply)),
        LocationData("Tainted Bethany (Mother)", 0x27BC87F6, "Corpse",
                     lambda state: has("The Zealot", state, world, ply)),
        LocationData("Tainted Bethany (The Beast)", 0x27BC87F7, "Ascent",
                     lambda state: has("The Zealot", state, world, ply)),
        LocationData("Tainted Bethany (Ultra Greed)", 0x27BC87F8, "Greed Mode",
                     lambda state: has("The Zealot", state, world, ply)),
        LocationData("Tainted Bethany (Ultra Greedier)", 0x27BC87F9, "Greedier Mode",
                     lambda state: has("The Zealot", state, world, ply)),
        LocationData("Jacob and Esau (Boss Rush)", 0x27BC87FA, "Chapter 3",
                     lambda state: has("Jacob and Esau", state, world, ply)),
        LocationData("Jacob and Esau (Mom's Heart)", 0x27BC87FB, "Chapter 4",
                     lambda state: has("Jacob and Esau", state, world, ply)),
        LocationData("Jacob and Esau (Satan)", 0x27BC87FC, "Sheol",
                     lambda state: has("Jacob and Esau", state, world, ply)),
        LocationData("Jacob and Esau (Isaac)", 0x27BC87FD, "Cathedral",
                     lambda state: has("Jacob and Esau", state, world, ply)),
        LocationData("Jacob and Esau (???)", 0x27BC87FE, "The Chest",
                     lambda state: has("Jacob and Esau", state, world, ply)),
        LocationData("Jacob and Esau (The Lamb)", 0x27BC87FF, "Dark Room",
                     lambda state: has("Jacob and Esau", state, world, ply)),
        LocationData("Jacob and Esau (Mega Satan)", 0x27BC8800, "Mega Satan",
                     lambda state: has("Jacob and Esau", state, world, ply)),
        LocationData("Jacob and Esau (Hush)", 0x27BC8801, "Blue Womb",
                     lambda state: has("Jacob and Esau", state, world, ply)),
        LocationData("Jacob and Esau (Delirium)", 0x27BC8802, "The Void",
                     lambda state: has("Jacob and Esau", state, world, ply)),
        LocationData("Jacob and Esau (Mother)", 0x27BC8803, "Corpse",
                     lambda state: has("Jacob and Esau", state, world, ply)),
        LocationData("Jacob and Esau (The Beast)", 0x27BC8804, "Ascent",
                     lambda state: has("Jacob and Esau", state, world, ply)),
        LocationData("Jacob and Esau (Ultra Greed)", 0x27BC8805, "Greed Mode",
                     lambda state: has("Jacob and Esau", state, world, ply)),
        LocationData("Jacob and Esau (Ultra Greedier)", 0x27BC8806, "Greedier Mode",
                     lambda state: has("Jacob and Esau", state, world, ply)),
        LocationData("Tainted Jacob and Esau (??? & Lamb)", 0x27BC8807, "Dark Room",
                     lambda state: has("The Deserter", state, world, ply) and can_reach_bluebaby_and_lamb(ply, state)),
        LocationData("Tainted Jacob and Esau (Mega Satan)", 0x27BC8808, "Mega Satan",
                     lambda state: has("The Deserter", state, world, ply)),
        LocationData("Tainted Jacob and Esau (Hush & Boss Rush)", 0x27BC8809, "Blue Womb",
                     lambda state: has("The Deserter", state, world, ply)),
        LocationData("Tainted Jacob and Esau (Delirium)", 0x27BC880A, "The Void",
                     lambda state: has("The Deserter", state, world, ply)),
        LocationData("Tainted Jacob and Esau (Mother)", 0x27BC880B, "Corpse",
                     lambda state: has("The Deserter", state, world, ply)),
        LocationData("Tainted Jacob and Esau (The Beast)", 0x27BC880C, "Ascent",
                     lambda state: has("The Deserter", state, world, ply)),
        LocationData("Tainted Jacob and Esau (Ultra Greed)", 0x27BC880D, "Greed Mode",
                     lambda state: has("The Deserter", state, world, ply)),
        LocationData("Tainted Jacob and Esau (Ultra Greedier)", 0x27BC880E, "Greedier Mode",
                     lambda state: has("The Deserter", state, world, ply)),

        LocationData("Isaac (All Marks)", 0x27B25A80, "Mega Satan",
                     lambda state: has("Isaac", state, world, ply) and can_reach_all_marks(ply, state), category="All Marks"),
        LocationData("Magdalene (All Marks)", 0x27B25A81, "Mega Satan",
                     lambda state: has("Magdalene", state, world, ply) and can_reach_all_marks(ply, state), category="All Marks"),
        LocationData("Cain (All Marks)", 0x27B25A82, "Mega Satan",
                     lambda state: has("Cain", state, world, ply) and can_reach_all_marks(ply, state), category="All Marks"),
        LocationData("Judas (All Marks)", 0x27B25A83, "Mega Satan",
                     lambda state: has("Judas", state, world, ply) and can_reach_all_marks(ply, state), category="All Marks"),
        LocationData("??? (All Marks)", 0x27B25A84, "Mega Satan",
                     lambda state: has("???", state, world, ply) and can_reach_all_marks(ply, state), category="All Marks"),
        LocationData("Eve (All Marks)", 0x27B25A85, "Mega Satan",
                     lambda state: has("Eve", state, world, ply) and can_reach_all_marks(ply, state), category="All Marks"),
        LocationData("Samson (All Marks)", 0x27B25A86, "Mega Satan",
                     lambda state: has("Samson", state, world, ply) and can_reach_all_marks(ply, state), category="All Marks"),
        LocationData("Azazel (All Marks)", 0x27B25A87, "Mega Satan",
                     lambda state: has("Azazel", state, world, ply) and can_reach_all_marks(ply, state), category="All Marks"),
        LocationData("Lazarus (All Marks)", 0x27B25A88, "Mega Satan",
                     lambda state: has("Lazarus", state, world, ply) and can_reach_all_marks(ply, state), category="All Marks"),
        LocationData("Eden (All Marks)", 0x27B25A89, "Mega Satan",
                     lambda state: has("Eden", state, world, ply) and can_reach_all_marks(ply, state), category="All Marks"),
        LocationData("Lost (All Marks)", 0x27B25A8A, "Mega Satan",
                     lambda state: has("Lost", state, world, ply) and can_reach_all_marks(ply, state), category="All Marks"),
        LocationData("Lilith (All Marks)", 0x27B25A8B, "Mega Satan",
                     lambda state: has("Lilith", state, world, ply) and can_reach_all_marks(ply, state), category="All Marks"),
        LocationData("Keeper (All Marks)", 0x27B25A8C, "Mega Satan",
                     lambda state: has("Keeper", state, world, ply) and can_reach_all_marks(ply, state), category="All Marks"),
        LocationData("Apollyon (All Marks)", 0x27B25A8D, "Mega Satan",
                     lambda state: has("Apollyon", state, world, ply) and can_reach_all_marks(ply, state), category="All Marks"),
        LocationData("Forgotten (All Marks)", 0x27B25A8E, "Mega Satan",
                     lambda state: has("Forgotten", state, world, ply) and can_reach_all_marks(ply, state), category="All Marks"),
        LocationData("Bethany (All Marks)", 0x27B25A8F, "Mega Satan",
                     lambda state: has("Bethany", state, world, ply) and can_reach_all_marks(ply, state), category="All Marks"),
        LocationData("Jacob and Esau (All Marks)", 0x27B25A90, "Mega Satan",
                     lambda state: has("Jacob and Esau", state, world, ply) and can_reach_all_marks(ply, state), category="All Marks"),

        ################################################################################################################
        #   EVERYTHING ELSE
        ################################################################################################################
        LocationData("Chapter 1 Cleared", 0x27BC880F, "Chapter 1"),
        LocationData("Chapter 2 Cleared", 0x27BC8810, "Chapter 2"),
        LocationData("Chapter 3 Cleared", 0x27BC8811, "Chapter 3"),
        LocationData("Chapter 6 Cleared", 0x27BC8812, "Chapter 6"),
        LocationData("Chapter 1 Cleared (No Damage)", 0x27BC8813, "Chapter 1"),
        LocationData("Chapter 2 Cleared (No Damage)", 0x27BC8814, "Chapter 2"),
        LocationData("Chapter 3 Cleared (No Damage)", 0x27BC8815, "Chapter 3"),
        LocationData("Chapter 4 Cleared (No Damage)", 0x27BC8816, "Chapter 4"),
        LocationData("Chapter 6 Cleared (No Damage)", 0x27BC8817, "Chapter 6"),
        LocationData("Basement Cleared 40 Times", 0x27BC8818, "Basement"),
        LocationData("Chapter 2 Cleared 30 Times", 0x27BC8819, "Chapter 2"),
        LocationData("Chapter 3 Cleared 20 Times", 0x27BC881A, "Chapter 3"),
        LocationData("Chapter >1 Cleared w/ Only 0.5 Hearts", 0x27BC881B, "Chapter 2"),
        LocationData("Krampus Defeated", 0x27BC881C, "Menu"),
        LocationData("Baby Plum Defeated (10x)", 0x27BC881D, "Chapter 1"),
        LocationData("Baby Plum Spared", 0x27BC881E, "Chapter 1"),
        LocationData("Hornfel Killed", 0x27BC881F, "Mines"),
        LocationData("Lokii Defeated", 0x27BC8820, "Chapter 4"),
        LocationData("All 7 Sins Defeated", 0x27BC8821, "Menu"),
        LocationData("Any Harbinger Defeated", 0x27BC8822, "Menu"),
        LocationData("All 5 Harbingers Defeated", 0x27BC8823, "Chapter 4"),
        LocationData("Angel Defeated (10x)", 0x27BC8824, "Menu"),
        LocationData("??? and The Lamb Defeated", 0x27BC8825, "Dark Room",
                     lambda state: can_reach_bluebaby_and_lamb(ply, state)),
        LocationData("Hush Defeated", 0x27BC8826, "Blue Womb"),
        LocationData("Hush Defeated (3x)", 0x27BC8827, "Blue Womb"),
        LocationData("Mom's Heart Defeated", 0x27BC8828, "Chapter 4"),
        LocationData("Mom's Heart Defeated (2x)", 0x27BC8829, "Chapter 4"),
        LocationData("Mom's Heart Defeated (3x)", 0x27BC882A, "Chapter 4"),
        LocationData("Mom's Heart Defeated (4x)", 0x27BC882B, "Chapter 4"),
        LocationData("Mom's Heart Defeated (5x)", 0x27BC882C, "Chapter 4"),
        LocationData("Mom's Heart Defeated (6x)", 0x27BC882D, "Chapter 4"),
        LocationData("Mom's Heart Defeated (7x)", 0x27BC882E, "Chapter 4"),
        LocationData("Mom's Heart Defeated (8x)", 0x27BC882F, "Chapter 4"),
        LocationData("Mom's Heart Defeated (9x)", 0x27BC8830, "Chapter 4"),
        LocationData("Mom's Heart Defeated (10x)", 0x27BC8831, "Chapter 4"),
        LocationData("Mom's Heart Defeated (11x)", 0x27BC8832, "Chapter 4"),
        LocationData("Mom's Heart Defeated (As Lazarus w/ No Deaths)", 0x27BC8833, "Chapter 4",
                     lambda state: has("Lazarus", state, world, ply)),
        LocationData("Satan Defeated", 0x27BC8834, "Sheol"),
        LocationData("Satan Defeated (5x)", 0x27BC8835, "Sheol"),
        LocationData("The Lamb Defeated (<20 Minutes)", 0x27BC8836, "Dark Room"),
        LocationData("Isaac Defeated (5x)", 0x27BC8837, "Cathedral"),
        LocationData("Isaac Defeated (10x)", 0x27BC8838, "Cathedral"),
        LocationData("Mother Defeated", 0x27BC8839, "Corpse"),
        LocationData("Mega Satan Defeated", 0x27BC883A, "Mega Satan"),
        LocationData("Ultra Greed Defeated (As Azazel)", 0x27BC883B, "Greed Mode",
                     lambda state: has("Azazel", state, world, ply)),
        LocationData("Corpse Entered", 0x27BC883C, "Corpse"),
        LocationData("4 Soul Hearts", 0x27BC883D, "Menu"),
        LocationData("55 Coins", 0x27BC883E, "Menu"),
        LocationData("7 Heart Containers", 0x27BC883F, "Menu"),
        LocationData("No Hearts For Two Floors", 0x27BC8840, "Menu"),
        LocationData("No Damage For Two Floors", 0x27BC8841, "Menu"),
        LocationData("Died In Sacrifice Room w/ Missing Poster", 0x27BC8842, "Menu",
                     lambda state: has("Missing Poster", state, world, ply)),
        LocationData("Dark Room Mom's Shovel Spot", 0x27BC8843, "Dark Room"),
        #LocationData("Tainted Isaac Unlock", 0x27BC8844, "Ascent"),
        LocationData("Tainted Isaac Unlock", 0x27BC8845, "Ascent"),
        LocationData("Tainted Magdalene Unlock", 0x27BC8846, "Ascent",
                     lambda state: has("Magdalene", state, world, ply)),
        LocationData("Tainted Cain Unlock", 0x27BC8847, "Ascent",
                     lambda state: has("Cain", state, world, ply)),
        LocationData("Tainted Judas Unlock", 0x27BC8848, "Ascent",
                     lambda state: has("Judas", state, world, ply)),
        LocationData("Tainted ??? Unlock", 0x27BC8849, "Ascent",
                     lambda state: has("???", state, world, ply)),
        LocationData("Tainted Eve Unlock", 0x27BC884A, "Ascent",
                     lambda state: has("Eve", state, world, ply)),
        LocationData("Tainted Samson Unlock", 0x27BC884B, "Ascent",
                     lambda state: has("Samson", state, world, ply)),
        LocationData("Tainted Azazel Unlock", 0x27BC884C, "Ascent",
                     lambda state: has("Azazel", state, world, ply)),
        LocationData("Tainted Lazarus Unlock", 0x27BC884D, "Ascent",
                     lambda state: has("Lazarus", state, world, ply)),
        LocationData("Tainted Eden Unlock", 0x27BC884E, "Ascent",
                     lambda state: has("Eden", state, world, ply)),
        LocationData("Tainted Lost Unlock", 0x27BC884F, "Ascent",
                     lambda state: has("Lost", state, world, ply)),
        LocationData("Tainted Lilith Unlock", 0x27BC8850, "Ascent",
                     lambda state: has("Lilith", state, world, ply)),
        LocationData("Tainted Keeper Unlock", 0x27BC8851, "Ascent",
                     lambda state: has("Keeper", state, world, ply)),
        LocationData("Tainted Apollyon Unlock", 0x27BC8852, "Ascent",
                     lambda state: has("Apollyon", state, world, ply)),
        LocationData("Tainted Forgotten Unlock", 0x27BC8853, "Ascent",
                     lambda state: has("Forgotten", state, world, ply)),
        LocationData("Tainted Bethany Unlock", 0x27BC8854, "Ascent",
                     lambda state: has("Bethany", state, world, ply)),
        LocationData("Tainted Jacob Unlock", 0x27BC8855, "Ascent",
                     lambda state: has("Jacob and Esau", state, world, ply)),
        LocationData("Tinted Rock Destroyed (10x)", 0x27BC8856, "Menu"),
        LocationData("Tinted Rock Destroyed (100x)", 0x27BC8857, "Menu"),
        LocationData("Super Bandage Girl Made", 0x27BC8858, "Chapter 4",
                     lambda state: has("Ball of Bandages", state, world, ply)),
        LocationData("Arcade Visited (10x)", 0x27BC8859, "Menu"),
        LocationData("Bible Used on Mom", 0x27BC885A, "Chapter 3"),
        LocationData("Death (100x)", 0x27BC885B, "Menu"),
        LocationData("Dead Items Collected (2x)", 0x27BC885C, "Menu"),
        LocationData("Mom Items Collected (3x)", 0x27BC885D, "Menu"),
        LocationData("XIII - Death Used (4x)", 0x27BC885E, "Menu"),
        LocationData("Shopkeepers Exploded (20x)", 0x27BC885F, "Menu"),
        LocationData("Shell Game Played (100x)", 0x27BC8860, "Menu"),
        LocationData("Devil Deals Taken (3x In One Run)", 0x27BC8861, "Menu"),
        LocationData("Devil Deals Taken (20x)", 0x27BC8862, "Menu"),
        LocationData("Devil Deals Taken (25x)", 0x27BC8863, "Menu"),
        LocationData("Devil Deals Taken (30x)", 0x27BC8864, "Menu"),
        LocationData("Poop Destroyed (100x)", 0x27BC8865, "Menu"),
        LocationData("Syringe Items Collected (2x)", 0x27BC8866, "Menu"),
        LocationData("Battery Items Collected (2x)", 0x27BC8867, "Menu"),
        LocationData("Technology Items Collected (2x)", 0x27BC8868, "Menu"),
        LocationData("Key Pieces Collected", 0x27BC8869, "Menu",
                     lambda state: has("Angels", state, world, ply)),
        LocationData("Celestial Items Collected (3x)", 0x27BC886A, "Menu"),
        LocationData("Locked Chest Opened (20x)", 0x27BC886B, "Menu"),
        LocationData("Blood Donated (30x)", 0x27BC886C, "Menu"),
        LocationData("Slot Machine Exploded (30x)", 0x27BC886D, "Menu"),
        LocationData("Win Streak (3x)", 0x27BC886E, "Chapter 6"),
        LocationData("Win Streak (5x)", 0x27BC886F, "Chapter 6"),
        LocationData("Bestiary Completed", 0x27BC8870, "Ascent"),
        LocationData("It's The Key", 0x27BC8871, "Dark Room"),
        LocationData("Reset (7x)", 0x27BC8872, "Menu"),
        LocationData("Items Owned At Once (50x)", 0x27BC8873, "Menu"),
        LocationData("Secret Room Found (50x)", 0x27BC8874, "Menu"),
        LocationData("Blood Clot Collected (10x)", 0x27BC8875, "Menu"),
        LocationData("Tears Up Collected (10x)", 0x27BC8876, "Menu"),
        LocationData("Shops Entered in One Run (6x)", 0x27BC8877, "Menu"),
        LocationData("Angel Items Taken (10x)", 0x27BC8878, "Menu"),
        LocationData("Angel Items Taken (25x)", 0x27BC8879, "Menu"),
        LocationData("Collected Battery, 9 Volt, & Car Battery", 0x27BC887A, "Menu"),
        LocationData("Rubber Cement Collected (5x)", 0x27BC887B, "Menu",
                     lambda state: has("Rubber Cement", state, world, ply)),
        LocationData("Exploded By Own Ipecac Shot", 0x27BC887C, "Menu",
                     lambda state: has("Ipecac", state, world, ply)),
        LocationData("Bed Slept In (10x)", 0x27BC887D, "Menu"),
        LocationData("Gulp Pill Used (5x)", 0x27BC887E, "Menu",
                     lambda state: has("Gulp!", state, world, ply)),
        LocationData("Enemies Charmed at Once (3x)", 0x27BC887F, "Menu"),
        LocationData("Blue Flies at Once (20x)", 0x27BC8880, "Menu"),
        LocationData("Get Temporary Homing w/ Homing", 0x27BC8881, "Menu"),
        LocationData("Exploded Siren's Skull", 0x27BC8882, "Mausoleum"),
        LocationData("Open Mom's Chest", 0x27BC8883, "Ascent"),
        LocationData("Battery Bum Payout (5x)", 0x27BC8884, "Menu"),
        LocationData("Battery Bum Exploded (10x)", 0x27BC8885, "Menu"),
        LocationData("$0.40 Spent in One Shop", 0x27BC8886, "Menu"),
        LocationData("$0.99 Spent in One Shop", 0x27BC8887, "Menu"),
        LocationData("Shop Donation (1x)", 0x27BC8888, "Menu"),
        LocationData("Shop Donation (2x)", 0x27BC8889, "Menu"),
        LocationData("Shop Donation (3x)", 0x27BC888A, "Menu"),
        LocationData("Shop Donation (4x)", 0x27BC888B, "Menu"),
        LocationData("Shop Donation (5x)", 0x27BC888C, "Menu"),
        LocationData("Shop Donation (6x)", 0x27BC888D, "Menu"),
        LocationData("Shop Donation (7x)", 0x27BC888E, "Menu"),
        LocationData("Shop Donation (8x)", 0x27BC888F, "Menu"),
        LocationData("Shop Donation (9x)", 0x27BC8890, "Menu"),
        LocationData("Shop Donation (10x)", 0x27BC8891, "Menu"),
        LocationData("Greed Donation (1x)", 0x27BC8892, "Greed Mode"),
        LocationData("Greed Donation (2x)", 0x27BC8893, "Greed Mode"),
        LocationData("Greed Donation (3x)", 0x27BC8894, "Greed Mode"),
        LocationData("Greed Donation (4x)", 0x27BC8895, "Greed Mode"),
        LocationData("Greed Donation (5x)", 0x27BC8896, "Greed Mode"),
        LocationData("Greed Donation (6x)", 0x27BC8897, "Greed Mode"),
        LocationData("Greed Donation (7x)", 0x27BC8898, "Greed Mode"),
        LocationData("Greed Donation (8x)", 0x27BC8899, "Greed Mode"),
        LocationData("Greed Donation (9x)", 0x27BC889A, "Greed Mode"),
        LocationData("Greed Donation (10x)", 0x27BC889B, "Greed Mode"),
        LocationData("Greed Donation (11x)", 0x27BC889C, "Greed Mode"),
        LocationData("Greed Donation (12x)", 0x27BC889D, "Greed Mode"),

        LocationData("Mega Satan Defeated (All Non-Tainted Characters)", 0x27BC889E, "Mega Satan",
                     lambda state: has_all_normal_characters(ply, state, world)),
        LocationData("All Non-Tainted Completion Marks", 0x27BC889F, "Mega Satan",
                     lambda state: has_all_normal_characters(ply, state, world) and can_reach_all_marks(ply, state), category="All Marks"),
        LocationData("All Completion Marks", 0x27BC88A0, "Mega Satan",
                     lambda state: has_all_characters(ply, state, world) and can_reach_all_marks(ply, state), category="All Marks"),

        LocationData("Blank Card Used While Holding XIX - The Sun", 0x27BC88A1, "Menu",
                     lambda state: has("Blank Card", state, world, ply)),
        LocationData("Portal Defeated (20x)", 0x27BC88A2, "The Void"),
        LocationData("Rock Destroyed (100x)", 0x27BC88A3, "Menu"),
        LocationData("Rock Destroyed (500x)", 0x27BC88A4, "Menu"),
        LocationData("Rainbow Poop Destroyed (5x)", 0x27BC88A5, "Menu"),
        LocationData("Familiars Collected in One Run (5x)", 0x27BC88A6, "Menu"),
        LocationData("Little Horn Defeated (20x)", 0x27BC88A7, "Menu"),
        LocationData("Lil' Batteries Picked Up (20x)", 0x27BC88A8, "Menu"),
        LocationData("Be Larger (3x)", 0x27BC88A9, "Menu"),
        LocationData("Bed Slept In", 0x27BC88AA, "Menu"),
        LocationData("Cards or Runes Used (20x)", 0x27BC88AB, "Menu"),
        LocationData("Stop Watch and Broken Stop Watch Collected)", 0x27BC88AC, "Menu",
                     lambda state: has("Stop Watch", state, world, ply)),
        LocationData("Pandora's Box Used in Dark Room", 0x27BC88AD, "Dark Room",
                     lambda state: has("Pandora's Box", state, world, ply)),

        LocationData("Defeat All Bosses In Basement", 0x27BC88AE, "Basement"),
        LocationData("Defeat All Bosses In Caves", 0x27BC88AF, "Caves"),
        LocationData("Defeat All Bosses In Depths", 0x27BC88B0, "Depths"),

        LocationData("Defeat All Bosses In Downpour", 0x27BC88B1, "Downpour"),
        LocationData("Defeat All Bosses In Mines", 0x27BC88B2, "Mines"),
        LocationData("Defeat All Bosses In Mausoleum", 0x27BC88B3, "Mausoleum"),

        LocationData("It Lives! Defeated (16x)", 0x27BC88B4, "Chapter 4",
                     lambda state: has("It Lives!", state, world, ply)),
        LocationData("It Lives! Defeated (21x)", 0x27BC88B5, "Chapter 4",
                     lambda state: has("It Lives!", state, world, ply)),
        LocationData("It Lives! Defeated (30x)", 0x27BC88B6, "Chapter 4",
                     lambda state: has("It Lives!", state, world, ply)),


        ################################################################################################################
        #   CHALLENGES (666999666+)
        ################################################################################################################
        LocationData("Challenge #1 (Pitch Black)", 0x27C19B72, "Chapter 3",
                     lambda state: has("Challenge #1 (Pitch Black)", state, world, ply), category="Challenge"),
        LocationData("Challenge #2 (High Brow)", 0x27C19B73, "Chapter 3",
                     lambda state: has("Challenge #2 (High Brow)", state, world, ply), category="Challenge"),
        LocationData("Challenge #3 (Head Trauma)", 0x27C19B74, "Chapter 3",
                     lambda state: has("Challenge #3 (Head Trauma)", state, world, ply), category="Challenge"),
        LocationData("Challenge #4 (Darkness Falls)", 0x27C19B75, "Sheol",
                     lambda state: has("Challenge #4 (Darkness Falls)", state, world, ply), category="Challenge"),
        LocationData("Challenge #5 (The Tank)", 0x27C19B76, "Chapter 3",
                     lambda state: has("Challenge #5 (The Tank)", state, world, ply), category="Challenge"),
        LocationData("Challenge #6 (Solar System)", 0x27C19B77, "Chapter 4",
                     lambda state: has("Challenge #6 (Solar System)", state, world, ply), category="Challenge"),
        LocationData("Challenge #7 (Suicide King)", 0x27C19B78, "Cathedral",
                     lambda state: has("Challenge #7 (Suicide King)", state, world, ply), category="Challenge"),
        LocationData("Challenge #8 (Cat Got Your Tongue)", 0x27C19B79, "Chapter 3",
                     lambda state: has("Challenge #8 (Cat Got Your Tongue)", state, world, ply), category="Challenge"),
        LocationData("Challenge #9 (Demo Man)", 0x27C19B7A, "Chapter 4",
                     lambda state: has("Challenge #9 (Demo Man)", state, world, ply), category="Challenge"),
        LocationData("Challenge #10 (Cursed!)", 0x27C19B7B, "Chapter 3",
                     lambda state: has("Challenge #10 (Cursed!)", state, world, ply), category="Challenge"),
        LocationData("Challenge #11 (Glass Cannon)", 0x27C19B7C, "Sheol",
                     lambda state: has("Challenge #11 (Glass Cannon)", state, world, ply), category="Challenge"),
        LocationData("Challenge #12 (When Life Gives You Lemons)", 0x27C19B7D, "Chapter 3",
                     lambda state: has("Challenge #12 (When Life Gives You Lemons)", state, world, ply), category="Challenge"),
        LocationData("Challenge #13 (Beans!)", 0x27C19B7E, "Chapter 3",
                     lambda state: has("Challenge #13 (Beans!)", state, world, ply), category="Challenge"),
        LocationData("Challenge #14 (It's in the Cards)", 0x27C19B7F, "Chapter 3",
                     lambda state: has("Challenge #14 (It's in the Cards)", state, world, ply), category="Challenge"),
        LocationData("Challenge #15 (Slow Roll)", 0x27C19B80, "Chapter 3",
                     lambda state: has("Challenge #15 (Slow Roll)", state, world, ply), category="Challenge"),
        LocationData("Challenge #16 (Computer Savvy)", 0x27C19B81, "Chapter 3",
                     lambda state: has("Challenge #16 (Computer Savvy)", state, world, ply), category="Challenge"),
        LocationData("Challenge #17 (Waka Waka)", 0x27C19B82, "Chapter 3",
                     lambda state: has("Challenge #17 (Waka Waka)", state, world, ply), category="Challenge"),
        LocationData("Challenge #18 (The Host)", 0x27C19B83, "Chapter 3",
                     lambda state: has("Challenge #18 (The Host)", state, world, ply), category="Challenge"),
        LocationData("Challenge #19 (The Family Man)", 0x27C19B84, "Cathedral",
                     lambda state: has("Challenge #19 (The Family Man)", state, world, ply), category="Challenge"),
        LocationData("Challenge #20 (Purist)", 0x27C19B85, "Chapter 4",
                     lambda state: has("Challenge #20 (Purist)", state, world, ply), category="Challenge"),

        LocationData("Challenge #21 (XXXXXXXXL)", 0x27C19B86, "Chapter 4",
                     lambda state: has("Challenge #21 (XXXXXXXXL)", state, world, ply), category="Challenge"),
        LocationData("Challenge #22 (SPEED!)", 0x27C19B87, "Chapter 4",
                     lambda state: has("Challenge #22 (SPEED!)", state, world, ply), category="Challenge"),
        LocationData("Challenge #23 (Blue Bomber)", 0x27C19B88, "Sheol",
                     lambda state: has("Challenge #23 (Blue Bomber)", state, world, ply), category="Challenge"),
        LocationData("Challenge #24 (PAY TO PLAY)", 0x27C19B89, "Cathedral",
                     lambda state: has("Challenge #24 (PAY TO PLAY)", state, world, ply), category="Challenge"),
        LocationData("Challenge #25 (Have a Heart)", 0x27C19B8A, "Chapter 4",
                     lambda state: has("Challenge #25 (Have a Heart)", state, world, ply), category="Challenge"),
        LocationData("Challenge #26 (I RULE!)", 0x27C19B8B, "Mega Satan",
                     lambda state: has("Challenge #26 (I RULE!)", state, world, ply), category="Challenge"),
        LocationData("Challenge #27 (BRAINS!)", 0x27C19B8C, "The Chest",
                     lambda state: has("Challenge #27 (BRAINS!)", state, world, ply), category="Challenge"),
        LocationData("Challenge #28 (PRIDE DAY!)", 0x27C19B8D, "Chapter 4",
                     lambda state: has("Challenge #28 (PRIDE DAY!)", state, world, ply), category="Challenge"),
        LocationData("Challenge #29 (Onan's Streak)", 0x27C19B8F, "Cathedral",
                     lambda state: has("Challenge #29 (Onan's Streak)", state, world, ply), category="Challenge"),
        LocationData("Challenge #30 (The Guardian)", 0x27C19B90, "Chapter 4",
                     lambda state: has("Challenge #30 (The Guardian)", state, world, ply), category="Challenge"),

        LocationData("Challenge #31 (Backasswards)", 0x27C19B91, "Mega Satan",
                     lambda state: has("Challenge #31 (Backasswards)", state, world, ply), category="Challenge"),
        LocationData("Challenge #32 (Aprils Fool)", 0x27C19B92, "Chapter 4",
                     lambda state: has("Challenge #32 (Aprils Fool)", state, world, ply), category="Challenge"),
        LocationData("Challenge #33 (Pokey Mans)", 0x27C19B93, "Cathedral",
                     lambda state: has("Challenge #33 (Pokey Mans)", state, world, ply), category="Challenge"),
        LocationData("Challenge #34 (Ultra Hard)", 0x27C19B94, "Mega Satan",
                     lambda state: has("Challenge #34 (Ultra Hard)", state, world, ply), category="Challenge"),
        LocationData("Challenge #35 (Pong)", 0x27C19B95, "The Chest",
                     lambda state: has("Challenge #35 (Pong)", state, world, ply), category="Challenge"),

        LocationData("Challenge #36 (Scat Man)", 0x27C19B96, "Chapter 4",
                     lambda state: has("Challenge #36 (Scat Man)", state, world, ply), category="Challenge"),
        LocationData("Challenge #37 (Bloody Mary)", 0x27C19B97, "Sheol",
                     lambda state: has("Challenge #37 (Bloody Mary)", state, world, ply), category="Challenge"),
        LocationData("Challenge #38 (Baptism by Fire)", 0x27C19B98, "Cathedral",
                     lambda state: has("Challenge #38 (Baptism by Fire)", state, world, ply), category="Challenge"),
        LocationData("Challenge #39 (Isaac's Awakening)", 0x27C19B99, "Corpse",
                     lambda state: has("Challenge #39 (Isaac's Awakening)", state, world, ply), category="Challenge"),
        LocationData("Challenge #40 (Seeing Double)", 0x27C19B9A, "Chapter 4",
                     lambda state: has("Challenge #40 (Seeing Double)", state, world, ply), category="Challenge"),
        LocationData("Challenge #41 (Pica Run)", 0x27C19B9B, "Cathedral",
                     lambda state: has("Challenge #41 (Pica Run)", state, world, ply), category="Challenge"),
        LocationData("Challenge #42 (Hot Potato)", 0x27C19B9C, "Sheol",
                     lambda state: has_all(["Challenge #42 (Hot Potato)", "The Fettered"], state, world, ply), category="Challenge"),
        LocationData("Challenge #43 (Cantripped!)", 0x27C19B9D, "Chapter 3",
                     lambda state: has_all(["Challenge #43 (Cantripped!)", "The Hoarder"], state, world, ply), category="Challenge"),
        LocationData("Challenge #44 (Red Redemption)", 0x27C19B9E, "Corpse",
                     lambda state: has_all(["Challenge #44 (Red Redemption)", "The Deserter"], state, world, ply), category="Challenge"),
        LocationData("Challenge #45 (DELETE THIS)", 0x27C19B9F, "The Chest",
                     lambda state: has("Challenge #45 (DELETE THIS)", state, world, ply), category="Challenge"),

        LocationData("All Co-Op Babies Found", 0x01, "Menu",
                     lambda state: state.has_group("Co-Op Baby", ply, floor(49 * (baby_ratio / 100))))
    ]

    # Add AP Consumable items
    ap_consumable_start_id = 666999999
    ap_consumable_count = 56

    for i in range(ap_consumable_count):
        locations.append(LocationData("AP Consumable ({i}x)".format(i=i + 1), ap_consumable_start_id, "Menu", progress_type=LocationProgressType.EXCLUDED))
        ap_consumable_start_id += 1

    if world is not None:
        # Exclude some locations

        greed_value = world.options.include_greed_mode.value
        for location in locations:

            # Remove challenges
            if not world.options.include_challenges and location.category == "Challenge":
                exclude_location(locations, location)

            # No Greed Mode? (Insert Megamind image)
            if greed_value != world.options.include_greed_mode.option_greed_and_greedier and (location.region in ["Greed Mode", "Greedier Mode"] or location.category == "All Marks"):
                if location.region == "Greed Mode" and greed_value == world.options.include_greed_mode.option_greed_mode_only:
                    continue

                if location.region == "Greedier Mode" and greed_value == world.options.include_greed_mode.option_greedier_mode_only:
                    continue

                exclude_location(locations, location)

    return locations

"""
Sets a location to "EXCLUDED" (Only filler)
"""
def exclude_location(locations: list[LocationData], location_data: LocationData):
    index = locations.index(location_data)

    locations[index] = LocationData(location_data.name, location_data.code, location_data.region, location_data.access_rule, location_data.category, LocationProgressType.EXCLUDED)